/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package PitneyBowes.Developer.ShippingApi;

import PitneyBowes.Developer.ApiException;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.AddressSuggestionResponse;
import org.openapitools.client.model.AddressVerifySuggest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddressValidationApi
 */
@Ignore
public class AddressValidationApiTest {

    private final AddressValidationApi api = new AddressValidationApi();

    
    /**
     * Address validation
     *
     * Address validation verifies and cleanses postal addresses within the United States to help ensure packages are rated accurately and shipments arrive at their final destinations on time.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyAddressTest() throws ApiException {
        Address address = null;
        Boolean xPBUnifiedErrorStructure = null;
        Boolean minimalAddressValidation = null;
        Address response = api.verifyAddress(address, xPBUnifiedErrorStructure, minimalAddressValidation);

        // TODO: test validations
    }
    
    /**
     * Address Suggestion
     *
     * This operation returns suggested addresses. Use this if the [Address Validation API](https://shipping.pitneybowes.com/api/post-address-verify.html) call has returned an error.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyAndSuggestAddressTest() throws ApiException {
        String returnSuggestions = null;
        AddressVerifySuggest addressVerifySuggest = null;
        Boolean xPBUnifiedErrorStructure = null;
        AddressSuggestionResponse response = api.verifyAndSuggestAddress(returnSuggestions, addressVerifySuggest, xPBUnifiedErrorStructure);

        // TODO: test validations
    }
    
}
