/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.pitneybowes.shippingapi.model.Errors;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CancelShipment
 */
public class CancelShipmentTest {
    private final CancelShipment model = new CancelShipment();

    /**
     * Model tests for CancelShipment
     */
    @Test
    public void testCancelShipment() {
        // TODO: test CancelShipment
    }

    /**
     * Test the property 'cancelInitiator'
     */
    @Test
    public void cancelInitiatorTest() {
        // TODO: test cancelInitiator
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'errorMessages'
     */
    @Test
    public void errorMessagesTest() {
        // TODO: test errorMessages
    }

    /**
     * Test the property 'parcelTrackingNumber'
     */
    @Test
    public void parcelTrackingNumberTest() {
        // TODO: test parcelTrackingNumber
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'totalCarrierCharge'
     */
    @Test
    public void totalCarrierChargeTest() {
        // TODO: test totalCarrierCharge
    }

}
