/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CrossBorderQuotesRequestPricingCodPrice
 */
public class CrossBorderQuotesRequestPricingCodPriceTest {
    private final CrossBorderQuotesRequestPricingCodPrice model = new CrossBorderQuotesRequestPricingCodPrice();

    /**
     * Model tests for CrossBorderQuotesRequestPricingCodPrice
     */
    @Test
    public void testCrossBorderQuotesRequestPricingCodPrice() {
        // TODO: test CrossBorderQuotesRequestPricingCodPrice
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'cod'
     */
    @Test
    public void codTest() {
        // TODO: test cod
    }

    /**
     * Test the property 'includesDuty'
     */
    @Test
    public void includesDutyTest() {
        // TODO: test includesDuty
    }

    /**
     * Test the property 'includesTaxes'
     */
    @Test
    public void includesTaxesTest() {
        // TODO: test includesTaxes
    }

}
