/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pitneybowes.shippingapi.model.CustomsInfo;
import org.pitneybowes.shippingapi.model.CustomsItem;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Customs
 */
public class CustomsTest {
    private final Customs model = new Customs();

    /**
     * Model tests for Customs
     */
    @Test
    public void testCustoms() {
        // TODO: test Customs
    }

    /**
     * Test the property 'customsInfo'
     */
    @Test
    public void customsInfoTest() {
        // TODO: test customsInfo
    }

    /**
     * Test the property 'customsItems'
     */
    @Test
    public void customsItemsTest() {
        // TODO: test customsItems
    }

}
