/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.pitneybowes.shippingapi.model.Address;
import org.pitneybowes.shippingapi.model.ParcelWeight;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomsItem
 */
public class CustomsItemTest {
    private final CustomsItem model = new CustomsItem();

    /**
     * Model tests for CustomsItem
     */
    @Test
    public void testCustomsItem() {
        // TODO: test CustomsItem
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'hSTariffCode'
     */
    @Test
    public void hSTariffCodeTest() {
        // TODO: test hSTariffCode
    }

    /**
     * Test the property 'netCostMethod'
     */
    @Test
    public void netCostMethodTest() {
        // TODO: test netCostMethod
    }

    /**
     * Test the property 'originCountryCode'
     */
    @Test
    public void originCountryCodeTest() {
        // TODO: test originCountryCode
    }

    /**
     * Test the property 'originStateProvince'
     */
    @Test
    public void originStateProvinceTest() {
        // TODO: test originStateProvince
    }

    /**
     * Test the property 'preferenceCriterion'
     */
    @Test
    public void preferenceCriterionTest() {
        // TODO: test preferenceCriterion
    }

    /**
     * Test the property 'producerAddress'
     */
    @Test
    public void producerAddressTest() {
        // TODO: test producerAddress
    }

    /**
     * Test the property 'producerDetermination'
     */
    @Test
    public void producerDeterminationTest() {
        // TODO: test producerDetermination
    }

    /**
     * Test the property 'producerId'
     */
    @Test
    public void producerIdTest() {
        // TODO: test producerId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'quantityUOM'
     */
    @Test
    public void quantityUOMTest() {
        // TODO: test quantityUOM
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'unitWeight'
     */
    @Test
    public void unitWeightTest() {
        // TODO: test unitWeight
    }

}
