/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pitneybowes.shippingapi.model.Address;
import org.pitneybowes.shippingapi.model.Document;
import org.pitneybowes.shippingapi.model.Parameter;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Manifest
 */
public class ManifestTest {
    private final Manifest model = new Manifest();

    /**
     * Model tests for Manifest
     */
    @Test
    public void testManifest() {
        // TODO: test Manifest
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'fromAddress'
     */
    @Test
    public void fromAddressTest() {
        // TODO: test fromAddress
    }

    /**
     * Test the property 'inductionPostalCode'
     */
    @Test
    public void inductionPostalCodeTest() {
        // TODO: test inductionPostalCode
    }

    /**
     * Test the property 'manifestId'
     */
    @Test
    public void manifestIdTest() {
        // TODO: test manifestId
    }

    /**
     * Test the property 'manifestTrackingNumber'
     */
    @Test
    public void manifestTrackingNumberTest() {
        // TODO: test manifestTrackingNumber
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'parcelTrackingNumbers'
     */
    @Test
    public void parcelTrackingNumbersTest() {
        // TODO: test parcelTrackingNumbers
    }

    /**
     * Test the property 'submissionDate'
     */
    @Test
    public void submissionDateTest() {
        // TODO: test submissionDate
    }

}
