/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionPolicyResponseSort
 */
public class ParcelProtectionPolicyResponseSortTest {
    private final ParcelProtectionPolicyResponseSort model = new ParcelProtectionPolicyResponseSort();

    /**
     * Model tests for ParcelProtectionPolicyResponseSort
     */
    @Test
    public void testParcelProtectionPolicyResponseSort() {
        // TODO: test ParcelProtectionPolicyResponseSort
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'property'
     */
    @Test
    public void propertyTest() {
        // TODO: test property
    }

    /**
     * Test the property 'ignoreCase'
     */
    @Test
    public void ignoreCaseTest() {
        // TODO: test ignoreCase
    }

    /**
     * Test the property 'nullHandling'
     */
    @Test
    public void nullHandlingTest() {
        // TODO: test nullHandling
    }

    /**
     * Test the property 'descending'
     */
    @Test
    public void descendingTest() {
        // TODO: test descending
    }

    /**
     * Test the property 'ascending'
     */
    @Test
    public void ascendingTest() {
        // TODO: test ascending
    }

}
