/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.pitneybowes.shippingapi.model.SchedulePickupTotalWeight;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SchedulePickupPickupSummary
 */
public class SchedulePickupPickupSummaryTest {
    private final SchedulePickupPickupSummary model = new SchedulePickupPickupSummary();

    /**
     * Model tests for SchedulePickupPickupSummary
     */
    @Test
    public void testSchedulePickupPickupSummary() {
        // TODO: test SchedulePickupPickupSummary
    }

    /**
     * Test the property 'serviceId'
     */
    @Test
    public void serviceIdTest() {
        // TODO: test serviceId
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'totalWeight'
     */
    @Test
    public void totalWeightTest() {
        // TODO: test totalWeight
    }

}
