/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.pitneybowes.shippingapi.model.Parameter;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SpecialService
 */
public class SpecialServiceTest {
    private final SpecialService model = new SpecialService();

    /**
     * Model tests for SpecialService
     */
    @Test
    public void testSpecialService() {
        // TODO: test SpecialService
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'inputParameters'
     */
    @Test
    public void inputParametersTest() {
        // TODO: test inputParameters
    }

    /**
     * Test the property 'specialServiceId'
     */
    @Test
    public void specialServiceIdTest() {
        // TODO: test specialServiceId
    }

}
