/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddTrackingEventsEvents
 */
public class AddTrackingEventsEventsTest {
    private final AddTrackingEventsEvents model = new AddTrackingEventsEvents();

    /**
     * Model tests for AddTrackingEventsEvents
     */
    @Test
    public void testAddTrackingEventsEvents() {
        // TODO: test AddTrackingEventsEvents
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'carrierEventCode'
     */
    @Test
    public void carrierEventCodeTest() {
        // TODO: test carrierEventCode
    }

    /**
     * Test the property 'eventDate'
     */
    @Test
    public void eventDateTest() {
        // TODO: test eventDate
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    public void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'eventTimeOffset'
     */
    @Test
    public void eventTimeOffsetTest() {
        // TODO: test eventTimeOffset
    }

    /**
     * Test the property 'eventCity'
     */
    @Test
    public void eventCityTest() {
        // TODO: test eventCity
    }

    /**
     * Test the property 'eventStateOrProvince'
     */
    @Test
    public void eventStateOrProvinceTest() {
        // TODO: test eventStateOrProvince
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
