/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CarrierFacilityRequestAddress;
import org.openapitools.client.model.CarrierFacilityResponseCarrierFacilityOptions;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CarrierFacilityRequest
 */
public class CarrierFacilityRequestTest {
    private final CarrierFacilityRequest model = new CarrierFacilityRequest();

    /**
     * Model tests for CarrierFacilityRequest
     */
    @Test
    public void testCarrierFacilityRequest() {
        // TODO: test CarrierFacilityRequest
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'carrierFacilityOptions'
     */
    @Test
    public void carrierFacilityOptionsTest() {
        // TODO: test carrierFacilityOptions
    }

}
