/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.InfectiousSubstanceContact;
import org.openapitools.client.model.RadioActivityDetail;
import org.openapitools.client.model.RadioNuclideDetail;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CommodityInfo
 */
public class CommodityInfoTest {
    private final CommodityInfo model = new CommodityInfo();

    /**
     * Model tests for CommodityInfo
     */
    @Test
    public void testCommodityInfo() {
        // TODO: test CommodityInfo
    }

    /**
     * Test the property 'cargoAirCraft'
     */
    @Test
    public void cargoAirCraftTest() {
        // TODO: test cargoAirCraft
    }

    /**
     * Test the property 'hazardClass'
     */
    @Test
    public void hazardClassTest() {
        // TODO: test hazardClass
    }

    /**
     * Test the property 'infectiousSubstanceContact'
     */
    @Test
    public void infectiousSubstanceContactTest() {
        // TODO: test infectiousSubstanceContact
    }

    /**
     * Test the property 'innerReceptaclesQuantity'
     */
    @Test
    public void innerReceptaclesQuantityTest() {
        // TODO: test innerReceptaclesQuantity
    }

    /**
     * Test the property 'innerReceptaclesQuantityUOM'
     */
    @Test
    public void innerReceptaclesQuantityUOMTest() {
        // TODO: test innerReceptaclesQuantityUOM
    }

    /**
     * Test the property 'packagingGroup'
     */
    @Test
    public void packagingGroupTest() {
        // TODO: test packagingGroup
    }

    /**
     * Test the property 'packagingInstructions'
     */
    @Test
    public void packagingInstructionsTest() {
        // TODO: test packagingInstructions
    }

    /**
     * Test the property 'percentage'
     */
    @Test
    public void percentageTest() {
        // TODO: test percentage
    }

    /**
     * Test the property 'properShippingName'
     */
    @Test
    public void properShippingNameTest() {
        // TODO: test properShippingName
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'quantityUOM'
     */
    @Test
    public void quantityUOMTest() {
        // TODO: test quantityUOM
    }

    /**
     * Test the property 'radioActivityDetail'
     */
    @Test
    public void radioActivityDetailTest() {
        // TODO: test radioActivityDetail
    }

    /**
     * Test the property 'radioNuclideDetail'
     */
    @Test
    public void radioNuclideDetailTest() {
        // TODO: test radioNuclideDetail
    }

    /**
     * Test the property 'reportableQuantity'
     */
    @Test
    public void reportableQuantityTest() {
        // TODO: test reportableQuantity
    }

    /**
     * Test the property 'technicalName'
     */
    @Test
    public void technicalNameTest() {
        // TODO: test technicalName
    }

    /**
     * Test the property 'unId'
     */
    @Test
    public void unIdTest() {
        // TODO: test unId
    }

}
