/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CrossBorderQuotesRequestAttributes;
import org.openapitools.client.model.CrossBorderQuotesRequestCategories;
import org.openapitools.client.model.CrossBorderQuotesRequestIdentifiers;
import org.openapitools.client.model.CrossBorderQuotesRequestItemDimension;
import org.openapitools.client.model.CrossBorderQuotesRequestPricing;
import org.openapitools.client.model.CrossBorderQuotesRequestUnitWeight;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CrossBorderQuotesRequestBasketItems
 */
public class CrossBorderQuotesRequestBasketItemsTest {
    private final CrossBorderQuotesRequestBasketItems model = new CrossBorderQuotesRequestBasketItems();

    /**
     * Model tests for CrossBorderQuotesRequestBasketItems
     */
    @Test
    public void testCrossBorderQuotesRequestBasketItems() {
        // TODO: test CrossBorderQuotesRequestBasketItems
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'longDescription'
     */
    @Test
    public void longDescriptionTest() {
        // TODO: test longDescription
    }

    /**
     * Test the property 'unitWeight'
     */
    @Test
    public void unitWeightTest() {
        // TODO: test unitWeight
    }

    /**
     * Test the property 'itemDimension'
     */
    @Test
    public void itemDimensionTest() {
        // TODO: test itemDimension
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'originCountryCode'
     */
    @Test
    public void originCountryCodeTest() {
        // TODO: test originCountryCode
    }

    /**
     * Test the property 'parentIdentifier'
     */
    @Test
    public void parentIdentifierTest() {
        // TODO: test parentIdentifier
    }

    /**
     * Test the property 'childIdentifier'
     */
    @Test
    public void childIdentifierTest() {
        // TODO: test childIdentifier
    }

    /**
     * Test the property 'kit'
     */
    @Test
    public void kitTest() {
        // TODO: test kit
    }

    /**
     * Test the property 'kitIdentifier'
     */
    @Test
    public void kitIdentifierTest() {
        // TODO: test kitIdentifier
    }

    /**
     * Test the property 'kitQuantity'
     */
    @Test
    public void kitQuantityTest() {
        // TODO: test kitQuantity
    }

    /**
     * Test the property 'manufacturer'
     */
    @Test
    public void manufacturerTest() {
        // TODO: test manufacturer
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'eccn'
     */
    @Test
    public void eccnTest() {
        // TODO: test eccn
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'pricing'
     */
    @Test
    public void pricingTest() {
        // TODO: test pricing
    }

    /**
     * Test the property 'hSTariffCode'
     */
    @Test
    public void hSTariffCodeTest() {
        // TODO: test hSTariffCode
    }

    /**
     * Test the property 'hSTariffCodeCountry'
     */
    @Test
    public void hSTariffCodeCountryTest() {
        // TODO: test hSTariffCodeCountry
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'imageUrls'
     */
    @Test
    public void imageUrlsTest() {
        // TODO: test imageUrls
    }

    /**
     * Test the property 'shipsAlone'
     */
    @Test
    public void shipsAloneTest() {
        // TODO: test shipsAlone
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'hazmats'
     */
    @Test
    public void hazmatsTest() {
        // TODO: test hazmats
    }

}
