/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeliveryCommitment
 */
public class DeliveryCommitmentTest {
    private final DeliveryCommitment model = new DeliveryCommitment();

    /**
     * Model tests for DeliveryCommitment
     */
    @Test
    public void testDeliveryCommitment() {
        // TODO: test DeliveryCommitment
    }

    /**
     * Test the property 'additionalDetails'
     */
    @Test
    public void additionalDetailsTest() {
        // TODO: test additionalDetails
    }

    /**
     * Test the property 'estimatedDeliveryDateTime'
     */
    @Test
    public void estimatedDeliveryDateTimeTest() {
        // TODO: test estimatedDeliveryDateTime
    }

    /**
     * Test the property 'guarantee'
     */
    @Test
    public void guaranteeTest() {
        // TODO: test guarantee
    }

    /**
     * Test the property 'maxEstimatedNumberOfDays'
     */
    @Test
    public void maxEstimatedNumberOfDaysTest() {
        // TODO: test maxEstimatedNumberOfDays
    }

    /**
     * Test the property 'minEstimatedNumberOfDays'
     */
    @Test
    public void minEstimatedNumberOfDaysTest() {
        // TODO: test minEstimatedNumberOfDays
    }

}
