/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BatteryDetails;
import org.openapitools.client.model.ContainerDetails;
import org.openapitools.client.model.Signatory;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HazmatDetails
 */
public class HazmatDetailsTest {
    private final HazmatDetails model = new HazmatDetails();

    /**
     * Model tests for HazmatDetails
     */
    @Test
    public void testHazmatDetails() {
        // TODO: test HazmatDetails
    }

    /**
     * Test the property 'batteryDetails'
     */
    @Test
    public void batteryDetailsTest() {
        // TODO: test batteryDetails
    }

    /**
     * Test the property 'commodityType'
     */
    @Test
    public void commodityTypeTest() {
        // TODO: test commodityType
    }

    /**
     * Test the property 'containerCount'
     */
    @Test
    public void containerCountTest() {
        // TODO: test containerCount
    }

    /**
     * Test the property 'containerDetails'
     */
    @Test
    public void containerDetailsTest() {
        // TODO: test containerDetails
    }

    /**
     * Test the property 'emergencyContactNumber'
     */
    @Test
    public void emergencyContactNumberTest() {
        // TODO: test emergencyContactNumber
    }

    /**
     * Test the property 'hazmatDocumentType'
     */
    @Test
    public void hazmatDocumentTypeTest() {
        // TODO: test hazmatDocumentType
    }

    /**
     * Test the property 'identicalContainers'
     */
    @Test
    public void identicalContainersTest() {
        // TODO: test identicalContainers
    }

    /**
     * Test the property 'offeror'
     */
    @Test
    public void offerorTest() {
        // TODO: test offeror
    }

    /**
     * Test the property 'packagingOption'
     */
    @Test
    public void packagingOptionTest() {
        // TODO: test packagingOption
    }

    /**
     * Test the property 'signatory'
     */
    @Test
    public void signatoryTest() {
        // TODO: test signatory
    }

}
