/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo;
import org.openapitools.client.model.ParcelProtectionQuoteRequestShipmentInfoParcelInfo;
import org.openapitools.client.model.ParcelProtectionQuoteRequestShipmentInfoShipperInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionQuoteRequestShipmentInfo
 */
public class ParcelProtectionQuoteRequestShipmentInfoTest {
    private final ParcelProtectionQuoteRequestShipmentInfo model = new ParcelProtectionQuoteRequestShipmentInfo();

    /**
     * Model tests for ParcelProtectionQuoteRequestShipmentInfo
     */
    @Test
    public void testParcelProtectionQuoteRequestShipmentInfo() {
        // TODO: test ParcelProtectionQuoteRequestShipmentInfo
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'serviceId'
     */
    @Test
    public void serviceIdTest() {
        // TODO: test serviceId
    }

    /**
     * Test the property 'insuranceCoverageValue'
     */
    @Test
    public void insuranceCoverageValueTest() {
        // TODO: test insuranceCoverageValue
    }

    /**
     * Test the property 'insuranceCoverageValueCurrency'
     */
    @Test
    public void insuranceCoverageValueCurrencyTest() {
        // TODO: test insuranceCoverageValueCurrency
    }

    /**
     * Test the property 'parcelInfo'
     */
    @Test
    public void parcelInfoTest() {
        // TODO: test parcelInfo
    }

    /**
     * Test the property 'shipperInfo'
     */
    @Test
    public void shipperInfoTest() {
        // TODO: test shipperInfo
    }

    /**
     * Test the property 'consigneeInfo'
     */
    @Test
    public void consigneeInfoTest() {
        // TODO: test consigneeInfo
    }

}
