/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionQuoteRequestShipmentInfoParcelInfo
 */
public class ParcelProtectionQuoteRequestShipmentInfoParcelInfoTest {
    private final ParcelProtectionQuoteRequestShipmentInfoParcelInfo model = new ParcelProtectionQuoteRequestShipmentInfoParcelInfo();

    /**
     * Model tests for ParcelProtectionQuoteRequestShipmentInfoParcelInfo
     */
    @Test
    public void testParcelProtectionQuoteRequestShipmentInfoParcelInfo() {
        // TODO: test ParcelProtectionQuoteRequestShipmentInfoParcelInfo
    }

    /**
     * Test the property 'commodityList'
     */
    @Test
    public void commodityListTest() {
        // TODO: test commodityList
    }

}
