/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionQuoteResponseParcelProtectionFeesBreakup
 */
public class ParcelProtectionQuoteResponseParcelProtectionFeesBreakupTest {
    private final ParcelProtectionQuoteResponseParcelProtectionFeesBreakup model = new ParcelProtectionQuoteResponseParcelProtectionFeesBreakup();

    /**
     * Model tests for ParcelProtectionQuoteResponseParcelProtectionFeesBreakup
     */
    @Test
    public void testParcelProtectionQuoteResponseParcelProtectionFeesBreakup() {
        // TODO: test ParcelProtectionQuoteResponseParcelProtectionFeesBreakup
    }

    /**
     * Test the property 'basePremium'
     */
    @Test
    public void basePremiumTest() {
        // TODO: test basePremium
    }

    /**
     * Test the property 'technologyFee'
     */
    @Test
    public void technologyFeeTest() {
        // TODO: test technologyFee
    }

}
