/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.ParcelProtectionQuoteResponseParcelProtectionFeesBreakup;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionQuoteResponse
 */
public class ParcelProtectionQuoteResponseTest {
    private final ParcelProtectionQuoteResponse model = new ParcelProtectionQuoteResponse();

    /**
     * Model tests for ParcelProtectionQuoteResponse
     */
    @Test
    public void testParcelProtectionQuoteResponse() {
        // TODO: test ParcelProtectionQuoteResponse
    }

    /**
     * Test the property 'parcelProtectionFees'
     */
    @Test
    public void parcelProtectionFeesTest() {
        // TODO: test parcelProtectionFees
    }

    /**
     * Test the property 'parcelProtectionFeesCurrencyCode'
     */
    @Test
    public void parcelProtectionFeesCurrencyCodeTest() {
        // TODO: test parcelProtectionFeesCurrencyCode
    }

    /**
     * Test the property 'parcelProtectionFeesBreakup'
     */
    @Test
    public void parcelProtectionFeesBreakupTest() {
        // TODO: test parcelProtectionFeesBreakup
    }

}
