/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParcelProtectionPolicyResponseShipperInfoAddress
 */
public class ParcelProtectionPolicyResponseShipperInfoAddressTest {
    private final ParcelProtectionPolicyResponseShipperInfoAddress model = new ParcelProtectionPolicyResponseShipperInfoAddress();

    /**
     * Model tests for ParcelProtectionPolicyResponseShipperInfoAddress
     */
    @Test
    public void testParcelProtectionPolicyResponseShipperInfoAddress() {
        // TODO: test ParcelProtectionPolicyResponseShipperInfoAddress
    }

    /**
     * Test the property 'street1'
     */
    @Test
    public void street1Test() {
        // TODO: test street1
    }

    /**
     * Test the property 'street2'
     */
    @Test
    public void street2Test() {
        // TODO: test street2
    }

    /**
     * Test the property 'street3'
     */
    @Test
    public void street3Test() {
        // TODO: test street3
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

}
