/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Carrier;
import org.openapitools.client.model.DeliveryCommitment;
import org.openapitools.client.model.Discount;
import org.openapitools.client.model.ParcelType;
import org.openapitools.client.model.ParcelWeight;
import org.openapitools.client.model.Services;
import org.openapitools.client.model.SpecialService;
import org.openapitools.client.model.Surcharge;
import org.openapitools.client.model.Tax;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Rate
 */
public class RateTest {
    private final Rate model = new Rate();

    /**
     * Model tests for Rate
     */
    @Test
    public void testRate() {
        // TODO: test Rate
    }

    /**
     * Test the property 'alternateBaseCharge'
     */
    @Test
    public void alternateBaseChargeTest() {
        // TODO: test alternateBaseCharge
    }

    /**
     * Test the property 'alternateTotalCharge'
     */
    @Test
    public void alternateTotalChargeTest() {
        // TODO: test alternateTotalCharge
    }

    /**
     * Test the property 'baseCharge'
     */
    @Test
    public void baseChargeTest() {
        // TODO: test baseCharge
    }

    /**
     * Test the property 'baseChargeTaxes'
     */
    @Test
    public void baseChargeTaxesTest() {
        // TODO: test baseChargeTaxes
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'deliveryCommitment'
     */
    @Test
    public void deliveryCommitmentTest() {
        // TODO: test deliveryCommitment
    }

    /**
     * Test the property 'destinationZone'
     */
    @Test
    public void destinationZoneTest() {
        // TODO: test destinationZone
    }

    /**
     * Test the property 'dimensionalWeight'
     */
    @Test
    public void dimensionalWeightTest() {
        // TODO: test dimensionalWeight
    }

    /**
     * Test the property 'discounts'
     */
    @Test
    public void discountsTest() {
        // TODO: test discounts
    }

    /**
     * Test the property 'inductionPostalCode'
     */
    @Test
    public void inductionPostalCodeTest() {
        // TODO: test inductionPostalCode
    }

    /**
     * Test the property 'parcelType'
     */
    @Test
    public void parcelTypeTest() {
        // TODO: test parcelType
    }

    /**
     * Test the property 'rateTypeId'
     */
    @Test
    public void rateTypeIdTest() {
        // TODO: test rateTypeId
    }

    /**
     * Test the property 'serviceId'
     */
    @Test
    public void serviceIdTest() {
        // TODO: test serviceId
    }

    /**
     * Test the property 'specialServices'
     */
    @Test
    public void specialServicesTest() {
        // TODO: test specialServices
    }

    /**
     * Test the property 'surcharges'
     */
    @Test
    public void surchargesTest() {
        // TODO: test surcharges
    }

    /**
     * Test the property 'totalCarrierCharge'
     */
    @Test
    public void totalCarrierChargeTest() {
        // TODO: test totalCarrierCharge
    }

    /**
     * Test the property 'totalTaxAmount'
     */
    @Test
    public void totalTaxAmountTest() {
        // TODO: test totalTaxAmount
    }

}
