/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AdditionalAddress;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.CarrierPayment;
import org.openapitools.client.model.Customs;
import org.openapitools.client.model.Document;
import org.openapitools.client.model.HazmatDetails;
import org.openapitools.client.model.Parameter;
import org.openapitools.client.model.Parcel;
import org.openapitools.client.model.Rate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Shipment
 */
public class ShipmentTest {
    private final Shipment model = new Shipment();

    /**
     * Model tests for Shipment
     */
    @Test
    public void testShipment() {
        // TODO: test Shipment
    }

    /**
     * Test the property 'additionalAddresses'
     */
    @Test
    public void additionalAddressesTest() {
        // TODO: test additionalAddresses
    }

    /**
     * Test the property 'altReturnAddress'
     */
    @Test
    public void altReturnAddressTest() {
        // TODO: test altReturnAddress
    }

    /**
     * Test the property 'carrierPayments'
     */
    @Test
    public void carrierPaymentsTest() {
        // TODO: test carrierPayments
    }

    /**
     * Test the property 'customs'
     */
    @Test
    public void customsTest() {
        // TODO: test customs
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'fromAddress'
     */
    @Test
    public void fromAddressTest() {
        // TODO: test fromAddress
    }

    /**
     * Test the property 'hazmatDetails'
     */
    @Test
    public void hazmatDetailsTest() {
        // TODO: test hazmatDetails
    }

    /**
     * Test the property 'parcel'
     */
    @Test
    public void parcelTest() {
        // TODO: test parcel
    }

    /**
     * Test the property 'parcelTrackingNumber'
     */
    @Test
    public void parcelTrackingNumberTest() {
        // TODO: test parcelTrackingNumber
    }

    /**
     * Test the property 'rates'
     */
    @Test
    public void ratesTest() {
        // TODO: test rates
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'shipmentId'
     */
    @Test
    public void shipmentIdTest() {
        // TODO: test shipmentId
    }

    /**
     * Test the property 'shipmentOptions'
     */
    @Test
    public void shipmentOptionsTest() {
        // TODO: test shipmentOptions
    }

    /**
     * Test the property 'shipmentType'
     */
    @Test
    public void shipmentTypeTest() {
        // TODO: test shipmentType
    }

    /**
     * Test the property 'soldToAddress'
     */
    @Test
    public void soldToAddressTest() {
        // TODO: test soldToAddress
    }

    /**
     * Test the property 'toAddress'
     */
    @Test
    public void toAddressTest() {
        // TODO: test toAddress
    }

}
