/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SpecialServiceCodes
 */
public class SpecialServiceCodesTest {
    /**
     * Model tests for SpecialServiceCodes
     */
    @Test
    public void testSpecialServiceCodes() {
        // TODO: test SpecialServiceCodes
    }

}
