/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TrackingAddress;
import org.openapitools.client.model.TrackingResponseScanDetailsList;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrackingResponse
 */
public class TrackingResponseTest {
    private final TrackingResponse model = new TrackingResponse();

    /**
     * Model tests for TrackingResponse
     */
    @Test
    public void testTrackingResponse() {
        // TODO: test TrackingResponse
    }

    /**
     * Test the property 'packageCount'
     */
    @Test
    public void packageCountTest() {
        // TODO: test packageCount
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

    /**
     * Test the property 'referenceNumber'
     */
    @Test
    public void referenceNumberTest() {
        // TODO: test referenceNumber
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

    /**
     * Test the property 'updatedTime'
     */
    @Test
    public void updatedTimeTest() {
        // TODO: test updatedTime
    }

    /**
     * Test the property 'shipDate'
     */
    @Test
    public void shipDateTest() {
        // TODO: test shipDate
    }

    /**
     * Test the property 'estimatedDeliveryDate'
     */
    @Test
    public void estimatedDeliveryDateTest() {
        // TODO: test estimatedDeliveryDate
    }

    /**
     * Test the property 'estimatedDeliveryTime'
     */
    @Test
    public void estimatedDeliveryTimeTest() {
        // TODO: test estimatedDeliveryTime
    }

    /**
     * Test the property 'deliveryDate'
     */
    @Test
    public void deliveryDateTest() {
        // TODO: test deliveryDate
    }

    /**
     * Test the property 'deliveryTime'
     */
    @Test
    public void deliveryTimeTest() {
        // TODO: test deliveryTime
    }

    /**
     * Test the property 'deliveryLocation'
     */
    @Test
    public void deliveryLocationTest() {
        // TODO: test deliveryLocation
    }

    /**
     * Test the property 'deliveryLocationDescription'
     */
    @Test
    public void deliveryLocationDescriptionTest() {
        // TODO: test deliveryLocationDescription
    }

    /**
     * Test the property 'signedBy'
     */
    @Test
    public void signedByTest() {
        // TODO: test signedBy
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'weightOUM'
     */
    @Test
    public void weightOUMTest() {
        // TODO: test weightOUM
    }

    /**
     * Test the property 'reattemptDate'
     */
    @Test
    public void reattemptDateTest() {
        // TODO: test reattemptDate
    }

    /**
     * Test the property 'reattemptTime'
     */
    @Test
    public void reattemptTimeTest() {
        // TODO: test reattemptTime
    }

    /**
     * Test the property 'destinationAddress'
     */
    @Test
    public void destinationAddressTest() {
        // TODO: test destinationAddress
    }

    /**
     * Test the property 'senderAddress'
     */
    @Test
    public void senderAddressTest() {
        // TODO: test senderAddress
    }

    /**
     * Test the property 'scanDetailsList'
     */
    @Test
    public void scanDetailsListTest() {
        // TODO: test scanDetailsList
    }

}
