/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pitneybowes.shippingapi.model.Address;
import org.pitneybowes.shippingapi.model.CarrierFacilityResponseCarrierFacilityOptions;
import org.pitneybowes.shippingapi.model.CarrierFacilityResponseCarrierFacilitySuggestions;

/**
 * CarrierFacilityResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-10T01:37:26.222+05:30[Asia/Calcutta]")
public class CarrierFacilityResponse {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Address address;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private String carrier;

  public static final String SERIALIZED_NAME_CARRIER_FACILITY_OPTIONS = "carrierFacilityOptions";
  @SerializedName(SERIALIZED_NAME_CARRIER_FACILITY_OPTIONS)
  private List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions = null;

  public static final String SERIALIZED_NAME_CARRIER_FACILITY_SUGGESTIONS = "carrierFacilitySuggestions";
  @SerializedName(SERIALIZED_NAME_CARRIER_FACILITY_SUGGESTIONS)
  private List<CarrierFacilityResponseCarrierFacilitySuggestions> carrierFacilitySuggestions = null;


  public CarrierFacilityResponse address(Address address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getAddress() {
    return address;
  }


  public void setAddress(Address address) {
    this.address = address;
  }


  public CarrierFacilityResponse carrier(String carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarrier() {
    return carrier;
  }


  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }


  public CarrierFacilityResponse carrierFacilityOptions(List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions) {
    
    this.carrierFacilityOptions = carrierFacilityOptions;
    return this;
  }

  public CarrierFacilityResponse addCarrierFacilityOptionsItem(CarrierFacilityResponseCarrierFacilityOptions carrierFacilityOptionsItem) {
    if (this.carrierFacilityOptions == null) {
      this.carrierFacilityOptions = new ArrayList<CarrierFacilityResponseCarrierFacilityOptions>();
    }
    this.carrierFacilityOptions.add(carrierFacilityOptionsItem);
    return this;
  }

   /**
   * Get carrierFacilityOptions
   * @return carrierFacilityOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CarrierFacilityResponseCarrierFacilityOptions> getCarrierFacilityOptions() {
    return carrierFacilityOptions;
  }


  public void setCarrierFacilityOptions(List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions) {
    this.carrierFacilityOptions = carrierFacilityOptions;
  }


  public CarrierFacilityResponse carrierFacilitySuggestions(List<CarrierFacilityResponseCarrierFacilitySuggestions> carrierFacilitySuggestions) {
    
    this.carrierFacilitySuggestions = carrierFacilitySuggestions;
    return this;
  }

  public CarrierFacilityResponse addCarrierFacilitySuggestionsItem(CarrierFacilityResponseCarrierFacilitySuggestions carrierFacilitySuggestionsItem) {
    if (this.carrierFacilitySuggestions == null) {
      this.carrierFacilitySuggestions = new ArrayList<CarrierFacilityResponseCarrierFacilitySuggestions>();
    }
    this.carrierFacilitySuggestions.add(carrierFacilitySuggestionsItem);
    return this;
  }

   /**
   * Get carrierFacilitySuggestions
   * @return carrierFacilitySuggestions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CarrierFacilityResponseCarrierFacilitySuggestions> getCarrierFacilitySuggestions() {
    return carrierFacilitySuggestions;
  }


  public void setCarrierFacilitySuggestions(List<CarrierFacilityResponseCarrierFacilitySuggestions> carrierFacilitySuggestions) {
    this.carrierFacilitySuggestions = carrierFacilitySuggestions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarrierFacilityResponse carrierFacilityResponse = (CarrierFacilityResponse) o;
    return Objects.equals(this.address, carrierFacilityResponse.address) &&
        Objects.equals(this.carrier, carrierFacilityResponse.carrier) &&
        Objects.equals(this.carrierFacilityOptions, carrierFacilityResponse.carrierFacilityOptions) &&
        Objects.equals(this.carrierFacilitySuggestions, carrierFacilityResponse.carrierFacilitySuggestions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, carrier, carrierFacilityOptions, carrierFacilitySuggestions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarrierFacilityResponse {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    carrierFacilityOptions: ").append(toIndentedString(carrierFacilityOptions)).append("\n");
    sb.append("    carrierFacilitySuggestions: ").append(toIndentedString(carrierFacilitySuggestions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

