/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeliveryCommitment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-10T01:37:26.222+05:30[Asia/Calcutta]")
public class DeliveryCommitment {
  public static final String SERIALIZED_NAME_ADDITIONAL_DETAILS = "additionalDetails";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DETAILS)
  private String additionalDetails;

  public static final String SERIALIZED_NAME_ESTIMATED_DELIVERY_DATE_TIME = "estimatedDeliveryDateTime";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_DELIVERY_DATE_TIME)
  private String estimatedDeliveryDateTime;

  public static final String SERIALIZED_NAME_GUARANTEE = "guarantee";
  @SerializedName(SERIALIZED_NAME_GUARANTEE)
  private String guarantee;

  public static final String SERIALIZED_NAME_MAX_ESTIMATED_NUMBER_OF_DAYS = "maxEstimatedNumberOfDays";
  @SerializedName(SERIALIZED_NAME_MAX_ESTIMATED_NUMBER_OF_DAYS)
  private String maxEstimatedNumberOfDays;

  public static final String SERIALIZED_NAME_MIN_ESTIMATED_NUMBER_OF_DAYS = "minEstimatedNumberOfDays";
  @SerializedName(SERIALIZED_NAME_MIN_ESTIMATED_NUMBER_OF_DAYS)
  private String minEstimatedNumberOfDays;


  public DeliveryCommitment additionalDetails(String additionalDetails) {
    
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Get additionalDetails
   * @return additionalDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAdditionalDetails() {
    return additionalDetails;
  }


  public void setAdditionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
  }


  public DeliveryCommitment estimatedDeliveryDateTime(String estimatedDeliveryDateTime) {
    
    this.estimatedDeliveryDateTime = estimatedDeliveryDateTime;
    return this;
  }

   /**
   * Get estimatedDeliveryDateTime
   * @return estimatedDeliveryDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEstimatedDeliveryDateTime() {
    return estimatedDeliveryDateTime;
  }


  public void setEstimatedDeliveryDateTime(String estimatedDeliveryDateTime) {
    this.estimatedDeliveryDateTime = estimatedDeliveryDateTime;
  }


  public DeliveryCommitment guarantee(String guarantee) {
    
    this.guarantee = guarantee;
    return this;
  }

   /**
   * Get guarantee
   * @return guarantee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGuarantee() {
    return guarantee;
  }


  public void setGuarantee(String guarantee) {
    this.guarantee = guarantee;
  }


  public DeliveryCommitment maxEstimatedNumberOfDays(String maxEstimatedNumberOfDays) {
    
    this.maxEstimatedNumberOfDays = maxEstimatedNumberOfDays;
    return this;
  }

   /**
   * Get maxEstimatedNumberOfDays
   * @return maxEstimatedNumberOfDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMaxEstimatedNumberOfDays() {
    return maxEstimatedNumberOfDays;
  }


  public void setMaxEstimatedNumberOfDays(String maxEstimatedNumberOfDays) {
    this.maxEstimatedNumberOfDays = maxEstimatedNumberOfDays;
  }


  public DeliveryCommitment minEstimatedNumberOfDays(String minEstimatedNumberOfDays) {
    
    this.minEstimatedNumberOfDays = minEstimatedNumberOfDays;
    return this;
  }

   /**
   * Get minEstimatedNumberOfDays
   * @return minEstimatedNumberOfDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMinEstimatedNumberOfDays() {
    return minEstimatedNumberOfDays;
  }


  public void setMinEstimatedNumberOfDays(String minEstimatedNumberOfDays) {
    this.minEstimatedNumberOfDays = minEstimatedNumberOfDays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryCommitment deliveryCommitment = (DeliveryCommitment) o;
    return Objects.equals(this.additionalDetails, deliveryCommitment.additionalDetails) &&
        Objects.equals(this.estimatedDeliveryDateTime, deliveryCommitment.estimatedDeliveryDateTime) &&
        Objects.equals(this.guarantee, deliveryCommitment.guarantee) &&
        Objects.equals(this.maxEstimatedNumberOfDays, deliveryCommitment.maxEstimatedNumberOfDays) &&
        Objects.equals(this.minEstimatedNumberOfDays, deliveryCommitment.minEstimatedNumberOfDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalDetails, estimatedDeliveryDateTime, guarantee, maxEstimatedNumberOfDays, minEstimatedNumberOfDays);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryCommitment {\n");
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("    estimatedDeliveryDateTime: ").append(toIndentedString(estimatedDeliveryDateTime)).append("\n");
    sb.append("    guarantee: ").append(toIndentedString(guarantee)).append("\n");
    sb.append("    maxEstimatedNumberOfDays: ").append(toIndentedString(maxEstimatedNumberOfDays)).append("\n");
    sb.append("    minEstimatedNumberOfDays: ").append(toIndentedString(minEstimatedNumberOfDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

