/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.pitneybowes.shippingapi.model.ParcelDimension;
import org.pitneybowes.shippingapi.model.ParcelWeight;

/**
 * Parcel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-10T01:37:26.222+05:30[Asia/Calcutta]")
public class Parcel {
  public static final String SERIALIZED_NAME_DIMENSION = "dimension";
  @SerializedName(SERIALIZED_NAME_DIMENSION)
  private ParcelDimension dimension;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  private ParcelWeight weight;

  public static final String SERIALIZED_NAME_VALUE_OF_GOODS = "valueOfGoods";
  @SerializedName(SERIALIZED_NAME_VALUE_OF_GOODS)
  private BigDecimal valueOfGoods;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;


  public Parcel dimension(ParcelDimension dimension) {
    
    this.dimension = dimension;
    return this;
  }

   /**
   * Get dimension
   * @return dimension
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelDimension getDimension() {
    return dimension;
  }


  public void setDimension(ParcelDimension dimension) {
    this.dimension = dimension;
  }


  public Parcel weight(ParcelWeight weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelWeight getWeight() {
    return weight;
  }


  public void setWeight(ParcelWeight weight) {
    this.weight = weight;
  }


  public Parcel valueOfGoods(BigDecimal valueOfGoods) {
    
    this.valueOfGoods = valueOfGoods;
    return this;
  }

   /**
   * Get valueOfGoods
   * @return valueOfGoods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getValueOfGoods() {
    return valueOfGoods;
  }


  public void setValueOfGoods(BigDecimal valueOfGoods) {
    this.valueOfGoods = valueOfGoods;
  }


  public Parcel currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Currency code as per [IOS 4217](https://en.wikipedia.org/wiki/ISO_4217)
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency code as per [IOS 4217](https://en.wikipedia.org/wiki/ISO_4217)")

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Parcel parcel = (Parcel) o;
    return Objects.equals(this.dimension, parcel.dimension) &&
        Objects.equals(this.weight, parcel.weight) &&
        Objects.equals(this.valueOfGoods, parcel.valueOfGoods) &&
        Objects.equals(this.currencyCode, parcel.currencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimension, weight, valueOfGoods, currencyCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Parcel {\n");
    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    valueOfGoods: ").append(toIndentedString(valueOfGoods)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

