/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.pitneybowes.shippingapi.model.ParcelProtectionCreateRequestShipmentInfo;

/**
 * ParcelProtectionCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-10T01:37:26.222+05:30[Asia/Calcutta]")
public class ParcelProtectionCreateRequest {
  public static final String SERIALIZED_NAME_PARCEL_PROTECTION_ACCOUNT_I_D = "parcelProtectionAccountID";
  @SerializedName(SERIALIZED_NAME_PARCEL_PROTECTION_ACCOUNT_I_D)
  private String parcelProtectionAccountID;

  public static final String SERIALIZED_NAME_PARCEL_PROTECTION_PROGRAM_I_D = "parcelProtectionProgramID";
  @SerializedName(SERIALIZED_NAME_PARCEL_PROTECTION_PROGRAM_I_D)
  private String parcelProtectionProgramID;

  public static final String SERIALIZED_NAME_SHIPMENT_INFO = "shipmentInfo";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_INFO)
  private ParcelProtectionCreateRequestShipmentInfo shipmentInfo;


  public ParcelProtectionCreateRequest parcelProtectionAccountID(String parcelProtectionAccountID) {
    
    this.parcelProtectionAccountID = parcelProtectionAccountID;
    return this;
  }

   /**
   * Get parcelProtectionAccountID
   * @return parcelProtectionAccountID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParcelProtectionAccountID() {
    return parcelProtectionAccountID;
  }


  public void setParcelProtectionAccountID(String parcelProtectionAccountID) {
    this.parcelProtectionAccountID = parcelProtectionAccountID;
  }


  public ParcelProtectionCreateRequest parcelProtectionProgramID(String parcelProtectionProgramID) {
    
    this.parcelProtectionProgramID = parcelProtectionProgramID;
    return this;
  }

   /**
   * Get parcelProtectionProgramID
   * @return parcelProtectionProgramID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParcelProtectionProgramID() {
    return parcelProtectionProgramID;
  }


  public void setParcelProtectionProgramID(String parcelProtectionProgramID) {
    this.parcelProtectionProgramID = parcelProtectionProgramID;
  }


  public ParcelProtectionCreateRequest shipmentInfo(ParcelProtectionCreateRequestShipmentInfo shipmentInfo) {
    
    this.shipmentInfo = shipmentInfo;
    return this;
  }

   /**
   * Get shipmentInfo
   * @return shipmentInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelProtectionCreateRequestShipmentInfo getShipmentInfo() {
    return shipmentInfo;
  }


  public void setShipmentInfo(ParcelProtectionCreateRequestShipmentInfo shipmentInfo) {
    this.shipmentInfo = shipmentInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelProtectionCreateRequest parcelProtectionCreateRequest = (ParcelProtectionCreateRequest) o;
    return Objects.equals(this.parcelProtectionAccountID, parcelProtectionCreateRequest.parcelProtectionAccountID) &&
        Objects.equals(this.parcelProtectionProgramID, parcelProtectionCreateRequest.parcelProtectionProgramID) &&
        Objects.equals(this.shipmentInfo, parcelProtectionCreateRequest.shipmentInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parcelProtectionAccountID, parcelProtectionProgramID, shipmentInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelProtectionCreateRequest {\n");
    sb.append("    parcelProtectionAccountID: ").append(toIndentedString(parcelProtectionAccountID)).append("\n");
    sb.append("    parcelProtectionProgramID: ").append(toIndentedString(parcelProtectionProgramID)).append("\n");
    sb.append("    shipmentInfo: ").append(toIndentedString(shipmentInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

