/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pitneybowes.shippingapi.api;

import org.pitneybowes.shippingapi.ApiException;
import org.pitneybowes.shippingapi.model.Errors;
import org.pitneybowes.shippingapi.model.ParcelProtectionCreateRequest;
import org.pitneybowes.shippingapi.model.ParcelProtectionCreateResponse;
import org.pitneybowes.shippingapi.model.ParcelProtectionPolicyResponse;
import org.pitneybowes.shippingapi.model.ParcelProtectionQuoteRequest;
import org.pitneybowes.shippingapi.model.ParcelProtectionQuoteResponse;
import org.pitneybowes.shippingapi.model.VoidParcelProtectionRequest;
import org.pitneybowes.shippingapi.model.VoidParcelProtectionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ParcelProtectionApi
 */
@Ignore
public class ParcelProtectionApiTest {

    private final ParcelProtectionApi api = new ParcelProtectionApi();

    
    /**
     * Parcel Protection Coverage
     *
     * This API lets merchants request Pitney Bowes [Parcel Protection](https://shipping.pitneybowes.com/faqs/parcel-protection.html) coverage for shipments. Merchants can request coverage for shipments created with the Shipping APIs as well as for shipments created with other platforms.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelParcelProtectionTest() throws ApiException {
        String xPBTransactionId = null;
        String parcelProtectionReferenceId = null;
        VoidParcelProtectionRequest voidParcelProtectionRequest = null;
        Boolean xPBUnifiedErrorStructure = null;
        VoidParcelProtectionResponse response = api.cancelParcelProtection(xPBTransactionId, parcelProtectionReferenceId, voidParcelProtectionRequest, xPBUnifiedErrorStructure);

        // TODO: test validations
    }
    
    /**
     * Parcel Protection Coverage
     *
     * This API lets merchants request Pitney Bowes [Parcel Protection](https://shipping.pitneybowes.com/faqs/parcel-protection.html) coverage for shipments. Merchants can request coverage for shipments created with the Shipping APIs as well as for shipments created with other platforms.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getParcelProtectionCoverageTest() throws ApiException {
        String xPBTransactionId = null;
        ParcelProtectionCreateRequest parcelProtectionCreateRequest = null;
        Boolean xPBUnifiedErrorStructure = null;
        ParcelProtectionCreateResponse response = api.getParcelProtectionCoverage(xPBTransactionId, parcelProtectionCreateRequest, xPBUnifiedErrorStructure);

        // TODO: test validations
    }
    
    /**
     * Parcel Protection Quote
     *
     * This API provides a quote for covering a shipment through Pitney Bowes [Parcel Protection](https://www.pitneybowes.com/us/ecommerce-delivery-services/parcel-protection.html).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getParcelProtectionQuoteTest() throws ApiException {
        String xPBTransactionId = null;
        ParcelProtectionQuoteRequest parcelProtectionQuoteRequest = null;
        Boolean xPBUnifiedErrorStructure = null;
        ParcelProtectionQuoteResponse response = api.getParcelProtectionQuote(xPBTransactionId, parcelProtectionQuoteRequest, xPBUnifiedErrorStructure);

        // TODO: test validations
    }
    
    /**
     * Parcel Protection Reports
     *
     * This operation retrieves the policy status and other information on the Parcel Protection policies you have purchased for your shipments. Further Details https://shipping.pitneybowes.com/api/get-parcel-protection-reports.html
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getParcelProtectionReportsTest() throws ApiException {
        String xPBTransactionId = null;
        String developerId = null;
        String policyCreatedFromDate = null;
        Boolean xPBUnifiedErrorStructure = null;
        String policyCreatedToDate = null;
        String policyReferenceId = null;
        String parcelTrackingNumber = null;
        String merchantId = null;
        String policyStatus = null;
        String size = null;
        String page = null;
        String sort = null;
        ParcelProtectionPolicyResponse response = api.getParcelProtectionReports(xPBTransactionId, developerId, policyCreatedFromDate, xPBUnifiedErrorStructure, policyCreatedToDate, policyReferenceId, parcelTrackingNumber, merchantId, policyStatus, size, page, sort);

        // TODO: test validations
    }
    
}
