/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Address;

/**
 * AddressSuggestionResponseSuggestions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-17T23:33:31.071+05:30[Asia/Calcutta]")
public class AddressSuggestionResponseSuggestions {
  public static final String SERIALIZED_NAME_SUGGESTION_TYPE = "suggestionType";
  @SerializedName(SERIALIZED_NAME_SUGGESTION_TYPE)
  private String suggestionType;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private List<Address> address = null;


  public AddressSuggestionResponseSuggestions suggestionType(String suggestionType) {
    
    this.suggestionType = suggestionType;
    return this;
  }

   /**
   * Get suggestionType
   * @return suggestionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSuggestionType() {
    return suggestionType;
  }


  public void setSuggestionType(String suggestionType) {
    this.suggestionType = suggestionType;
  }


  public AddressSuggestionResponseSuggestions address(List<Address> address) {
    
    this.address = address;
    return this;
  }

  public AddressSuggestionResponseSuggestions addAddressItem(Address addressItem) {
    if (this.address == null) {
      this.address = new ArrayList<Address>();
    }
    this.address.add(addressItem);
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Address> getAddress() {
    return address;
  }


  public void setAddress(List<Address> address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressSuggestionResponseSuggestions addressSuggestionResponseSuggestions = (AddressSuggestionResponseSuggestions) o;
    return Objects.equals(this.suggestionType, addressSuggestionResponseSuggestions.suggestionType) &&
        Objects.equals(this.address, addressSuggestionResponseSuggestions.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suggestionType, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressSuggestionResponseSuggestions {\n");
    sb.append("    suggestionType: ").append(toIndentedString(suggestionType)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

