/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatteryDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class BatteryDetails {
  public static final String SERIALIZED_NAME_BATTERY_MATERIAL = "batteryMaterial";
  @SerializedName(SERIALIZED_NAME_BATTERY_MATERIAL)
  private String batteryMaterial;

  public static final String SERIALIZED_NAME_BATTERY_PACKAGING = "batteryPackaging";
  @SerializedName(SERIALIZED_NAME_BATTERY_PACKAGING)
  private String batteryPackaging;

  public static final String SERIALIZED_NAME_REGULATORY = "regulatory";
  @SerializedName(SERIALIZED_NAME_REGULATORY)
  private String regulatory;


  public BatteryDetails batteryMaterial(String batteryMaterial) {
    
    this.batteryMaterial = batteryMaterial;
    return this;
  }

   /**
   * Get batteryMaterial
   * @return batteryMaterial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBatteryMaterial() {
    return batteryMaterial;
  }


  public void setBatteryMaterial(String batteryMaterial) {
    this.batteryMaterial = batteryMaterial;
  }


  public BatteryDetails batteryPackaging(String batteryPackaging) {
    
    this.batteryPackaging = batteryPackaging;
    return this;
  }

   /**
   * Get batteryPackaging
   * @return batteryPackaging
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBatteryPackaging() {
    return batteryPackaging;
  }


  public void setBatteryPackaging(String batteryPackaging) {
    this.batteryPackaging = batteryPackaging;
  }


  public BatteryDetails regulatory(String regulatory) {
    
    this.regulatory = regulatory;
    return this;
  }

   /**
   * Get regulatory
   * @return regulatory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRegulatory() {
    return regulatory;
  }


  public void setRegulatory(String regulatory) {
    this.regulatory = regulatory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatteryDetails batteryDetails = (BatteryDetails) o;
    return Objects.equals(this.batteryMaterial, batteryDetails.batteryMaterial) &&
        Objects.equals(this.batteryPackaging, batteryDetails.batteryPackaging) &&
        Objects.equals(this.regulatory, batteryDetails.regulatory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batteryMaterial, batteryPackaging, regulatory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatteryDetails {\n");
    sb.append("    batteryMaterial: ").append(toIndentedString(batteryMaterial)).append("\n");
    sb.append("    batteryPackaging: ").append(toIndentedString(batteryPackaging)).append("\n");
    sb.append("    regulatory: ").append(toIndentedString(regulatory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

