/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Errors;

/**
 * CancelShipment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class CancelShipment {
  public static final String SERIALIZED_NAME_CANCEL_INITIATOR = "cancelInitiator";
  @SerializedName(SERIALIZED_NAME_CANCEL_INITIATOR)
  private String cancelInitiator;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private String carrier;

  public static final String SERIALIZED_NAME_ERROR_MESSAGES = "errorMessages";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGES)
  private List<Errors> errorMessages = null;

  public static final String SERIALIZED_NAME_PARCEL_TRACKING_NUMBER = "parcelTrackingNumber";
  @SerializedName(SERIALIZED_NAME_PARCEL_TRACKING_NUMBER)
  private String parcelTrackingNumber;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TOTAL_CARRIER_CHARGE = "totalCarrierCharge";
  @SerializedName(SERIALIZED_NAME_TOTAL_CARRIER_CHARGE)
  private BigDecimal totalCarrierCharge;


  public CancelShipment cancelInitiator(String cancelInitiator) {
    
    this.cancelInitiator = cancelInitiator;
    return this;
  }

   /**
   * Get cancelInitiator
   * @return cancelInitiator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCancelInitiator() {
    return cancelInitiator;
  }


  public void setCancelInitiator(String cancelInitiator) {
    this.cancelInitiator = cancelInitiator;
  }


  public CancelShipment carrier(String carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarrier() {
    return carrier;
  }


  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }


  public CancelShipment errorMessages(List<Errors> errorMessages) {
    
    this.errorMessages = errorMessages;
    return this;
  }

  public CancelShipment addErrorMessagesItem(Errors errorMessagesItem) {
    if (this.errorMessages == null) {
      this.errorMessages = new ArrayList<Errors>();
    }
    this.errorMessages.add(errorMessagesItem);
    return this;
  }

   /**
   * Get errorMessages
   * @return errorMessages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Errors> getErrorMessages() {
    return errorMessages;
  }


  public void setErrorMessages(List<Errors> errorMessages) {
    this.errorMessages = errorMessages;
  }


  public CancelShipment parcelTrackingNumber(String parcelTrackingNumber) {
    
    this.parcelTrackingNumber = parcelTrackingNumber;
    return this;
  }

   /**
   * Get parcelTrackingNumber
   * @return parcelTrackingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParcelTrackingNumber() {
    return parcelTrackingNumber;
  }


  public void setParcelTrackingNumber(String parcelTrackingNumber) {
    this.parcelTrackingNumber = parcelTrackingNumber;
  }


  public CancelShipment status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public CancelShipment totalCarrierCharge(BigDecimal totalCarrierCharge) {
    
    this.totalCarrierCharge = totalCarrierCharge;
    return this;
  }

   /**
   * Get totalCarrierCharge
   * @return totalCarrierCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalCarrierCharge() {
    return totalCarrierCharge;
  }


  public void setTotalCarrierCharge(BigDecimal totalCarrierCharge) {
    this.totalCarrierCharge = totalCarrierCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelShipment cancelShipment = (CancelShipment) o;
    return Objects.equals(this.cancelInitiator, cancelShipment.cancelInitiator) &&
        Objects.equals(this.carrier, cancelShipment.carrier) &&
        Objects.equals(this.errorMessages, cancelShipment.errorMessages) &&
        Objects.equals(this.parcelTrackingNumber, cancelShipment.parcelTrackingNumber) &&
        Objects.equals(this.status, cancelShipment.status) &&
        Objects.equals(this.totalCarrierCharge, cancelShipment.totalCarrierCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelInitiator, carrier, errorMessages, parcelTrackingNumber, status, totalCarrierCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelShipment {\n");
    sb.append("    cancelInitiator: ").append(toIndentedString(cancelInitiator)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    errorMessages: ").append(toIndentedString(errorMessages)).append("\n");
    sb.append("    parcelTrackingNumber: ").append(toIndentedString(parcelTrackingNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalCarrierCharge: ").append(toIndentedString(totalCarrierCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

