/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CarrierFacilityRequestAddress;
import org.openapitools.client.model.CarrierFacilityResponseCarrierFacilityOptions;

/**
 * CarrierFacilityRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class CarrierFacilityRequest {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private CarrierFacilityRequestAddress address;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private String carrier;

  public static final String SERIALIZED_NAME_CARRIER_FACILITY_OPTIONS = "carrierFacilityOptions";
  @SerializedName(SERIALIZED_NAME_CARRIER_FACILITY_OPTIONS)
  private List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions = null;


  public CarrierFacilityRequest address(CarrierFacilityRequestAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CarrierFacilityRequestAddress getAddress() {
    return address;
  }


  public void setAddress(CarrierFacilityRequestAddress address) {
    this.address = address;
  }


  public CarrierFacilityRequest carrier(String carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarrier() {
    return carrier;
  }


  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }


  public CarrierFacilityRequest carrierFacilityOptions(List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions) {
    
    this.carrierFacilityOptions = carrierFacilityOptions;
    return this;
  }

  public CarrierFacilityRequest addCarrierFacilityOptionsItem(CarrierFacilityResponseCarrierFacilityOptions carrierFacilityOptionsItem) {
    if (this.carrierFacilityOptions == null) {
      this.carrierFacilityOptions = new ArrayList<CarrierFacilityResponseCarrierFacilityOptions>();
    }
    this.carrierFacilityOptions.add(carrierFacilityOptionsItem);
    return this;
  }

   /**
   * Get carrierFacilityOptions
   * @return carrierFacilityOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CarrierFacilityResponseCarrierFacilityOptions> getCarrierFacilityOptions() {
    return carrierFacilityOptions;
  }


  public void setCarrierFacilityOptions(List<CarrierFacilityResponseCarrierFacilityOptions> carrierFacilityOptions) {
    this.carrierFacilityOptions = carrierFacilityOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarrierFacilityRequest carrierFacilityRequest = (CarrierFacilityRequest) o;
    return Objects.equals(this.address, carrierFacilityRequest.address) &&
        Objects.equals(this.carrier, carrierFacilityRequest.carrier) &&
        Objects.equals(this.carrierFacilityOptions, carrierFacilityRequest.carrierFacilityOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, carrier, carrierFacilityOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarrierFacilityRequest {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    carrierFacilityOptions: ").append(toIndentedString(carrierFacilityOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

