/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.CrossBorderQuotesResponseUnitRatesDeliveryCommitment;

/**
 * CrossBorderQuotesResponseLineRates
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:03:32.867+05:30[Asia/Calcutta]")
public class CrossBorderQuotesResponseLineRates {
  public static final String SERIALIZED_NAME_LINE_PRICE = "linePrice";
  @SerializedName(SERIALIZED_NAME_LINE_PRICE)
  private BigDecimal linePrice;

  public static final String SERIALIZED_NAME_TOTAL_TAX_AMOUNT = "totalTaxAmount";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX_AMOUNT)
  private BigDecimal totalTaxAmount;

  public static final String SERIALIZED_NAME_TOTAL_DUTY_AMOUNT = "totalDutyAmount";
  @SerializedName(SERIALIZED_NAME_TOTAL_DUTY_AMOUNT)
  private Integer totalDutyAmount;

  public static final String SERIALIZED_NAME_SERVICE_ID = "serviceId";
  @SerializedName(SERIALIZED_NAME_SERVICE_ID)
  private String serviceId;

  public static final String SERIALIZED_NAME_BASE_CHARGE = "baseCharge";
  @SerializedName(SERIALIZED_NAME_BASE_CHARGE)
  private BigDecimal baseCharge;

  public static final String SERIALIZED_NAME_DELIVERY_COMMITMENT = "deliveryCommitment";
  @SerializedName(SERIALIZED_NAME_DELIVERY_COMMITMENT)
  private CrossBorderQuotesResponseUnitRatesDeliveryCommitment deliveryCommitment;

  public static final String SERIALIZED_NAME_TOTAL_CARRIER_CHARGE = "totalCarrierCharge";
  @SerializedName(SERIALIZED_NAME_TOTAL_CARRIER_CHARGE)
  private BigDecimal totalCarrierCharge;


  public CrossBorderQuotesResponseLineRates linePrice(BigDecimal linePrice) {
    
    this.linePrice = linePrice;
    return this;
  }

   /**
   * Get linePrice
   * @return linePrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getLinePrice() {
    return linePrice;
  }


  public void setLinePrice(BigDecimal linePrice) {
    this.linePrice = linePrice;
  }


  public CrossBorderQuotesResponseLineRates totalTaxAmount(BigDecimal totalTaxAmount) {
    
    this.totalTaxAmount = totalTaxAmount;
    return this;
  }

   /**
   * Get totalTaxAmount
   * @return totalTaxAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalTaxAmount() {
    return totalTaxAmount;
  }


  public void setTotalTaxAmount(BigDecimal totalTaxAmount) {
    this.totalTaxAmount = totalTaxAmount;
  }


  public CrossBorderQuotesResponseLineRates totalDutyAmount(Integer totalDutyAmount) {
    
    this.totalDutyAmount = totalDutyAmount;
    return this;
  }

   /**
   * Get totalDutyAmount
   * @return totalDutyAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalDutyAmount() {
    return totalDutyAmount;
  }


  public void setTotalDutyAmount(Integer totalDutyAmount) {
    this.totalDutyAmount = totalDutyAmount;
  }


  public CrossBorderQuotesResponseLineRates serviceId(String serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceId() {
    return serviceId;
  }


  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }


  public CrossBorderQuotesResponseLineRates baseCharge(BigDecimal baseCharge) {
    
    this.baseCharge = baseCharge;
    return this;
  }

   /**
   * Get baseCharge
   * @return baseCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBaseCharge() {
    return baseCharge;
  }


  public void setBaseCharge(BigDecimal baseCharge) {
    this.baseCharge = baseCharge;
  }


  public CrossBorderQuotesResponseLineRates deliveryCommitment(CrossBorderQuotesResponseUnitRatesDeliveryCommitment deliveryCommitment) {
    
    this.deliveryCommitment = deliveryCommitment;
    return this;
  }

   /**
   * Get deliveryCommitment
   * @return deliveryCommitment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CrossBorderQuotesResponseUnitRatesDeliveryCommitment getDeliveryCommitment() {
    return deliveryCommitment;
  }


  public void setDeliveryCommitment(CrossBorderQuotesResponseUnitRatesDeliveryCommitment deliveryCommitment) {
    this.deliveryCommitment = deliveryCommitment;
  }


  public CrossBorderQuotesResponseLineRates totalCarrierCharge(BigDecimal totalCarrierCharge) {
    
    this.totalCarrierCharge = totalCarrierCharge;
    return this;
  }

   /**
   * Get totalCarrierCharge
   * @return totalCarrierCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalCarrierCharge() {
    return totalCarrierCharge;
  }


  public void setTotalCarrierCharge(BigDecimal totalCarrierCharge) {
    this.totalCarrierCharge = totalCarrierCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrossBorderQuotesResponseLineRates crossBorderQuotesResponseLineRates = (CrossBorderQuotesResponseLineRates) o;
    return Objects.equals(this.linePrice, crossBorderQuotesResponseLineRates.linePrice) &&
        Objects.equals(this.totalTaxAmount, crossBorderQuotesResponseLineRates.totalTaxAmount) &&
        Objects.equals(this.totalDutyAmount, crossBorderQuotesResponseLineRates.totalDutyAmount) &&
        Objects.equals(this.serviceId, crossBorderQuotesResponseLineRates.serviceId) &&
        Objects.equals(this.baseCharge, crossBorderQuotesResponseLineRates.baseCharge) &&
        Objects.equals(this.deliveryCommitment, crossBorderQuotesResponseLineRates.deliveryCommitment) &&
        Objects.equals(this.totalCarrierCharge, crossBorderQuotesResponseLineRates.totalCarrierCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linePrice, totalTaxAmount, totalDutyAmount, serviceId, baseCharge, deliveryCommitment, totalCarrierCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrossBorderQuotesResponseLineRates {\n");
    sb.append("    linePrice: ").append(toIndentedString(linePrice)).append("\n");
    sb.append("    totalTaxAmount: ").append(toIndentedString(totalTaxAmount)).append("\n");
    sb.append("    totalDutyAmount: ").append(toIndentedString(totalDutyAmount)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    baseCharge: ").append(toIndentedString(baseCharge)).append("\n");
    sb.append("    deliveryCommitment: ").append(toIndentedString(deliveryCommitment)).append("\n");
    sb.append("    totalCarrierCharge: ").append(toIndentedString(totalCarrierCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

