/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CrossBorderQuotesRequestDescriptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-17T23:33:31.071+05:30[Asia/Calcutta]")
public class CrossBorderQuotesRequestDescriptions {
  public static final String SERIALIZED_NAME_LOCALE = "locale";
  @SerializedName(SERIALIZED_NAME_LOCALE)
  private String locale;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARENTS_NAMES = "parentsNames";
  @SerializedName(SERIALIZED_NAME_PARENTS_NAMES)
  private List<String> parentsNames = null;


  public CrossBorderQuotesRequestDescriptions locale(String locale) {
    
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocale() {
    return locale;
  }


  public void setLocale(String locale) {
    this.locale = locale;
  }


  public CrossBorderQuotesRequestDescriptions name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CrossBorderQuotesRequestDescriptions parentsNames(List<String> parentsNames) {
    
    this.parentsNames = parentsNames;
    return this;
  }

  public CrossBorderQuotesRequestDescriptions addParentsNamesItem(String parentsNamesItem) {
    if (this.parentsNames == null) {
      this.parentsNames = new ArrayList<String>();
    }
    this.parentsNames.add(parentsNamesItem);
    return this;
  }

   /**
   * Get parentsNames
   * @return parentsNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getParentsNames() {
    return parentsNames;
  }


  public void setParentsNames(List<String> parentsNames) {
    this.parentsNames = parentsNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrossBorderQuotesRequestDescriptions crossBorderQuotesRequestDescriptions = (CrossBorderQuotesRequestDescriptions) o;
    return Objects.equals(this.locale, crossBorderQuotesRequestDescriptions.locale) &&
        Objects.equals(this.name, crossBorderQuotesRequestDescriptions.name) &&
        Objects.equals(this.parentsNames, crossBorderQuotesRequestDescriptions.parentsNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locale, name, parentsNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrossBorderQuotesRequestDescriptions {\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentsNames: ").append(toIndentedString(parentsNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

