/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.ParcelWeight;

/**
 * CustomsItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class CustomsItem {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_H_S_TARIFF_CODE = "hSTariffCode";
  @SerializedName(SERIALIZED_NAME_H_S_TARIFF_CODE)
  private String hSTariffCode;

  /**
   * Gets or Sets netCostMethod
   */
  @JsonAdapter(NetCostMethodEnum.Adapter.class)
  public enum NetCostMethodEnum {
    NO_NET_COST("NO_NET_COST"),
    
    NET_COST("NET_COST");

    private String value;

    NetCostMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NetCostMethodEnum fromValue(String value) {
      for (NetCostMethodEnum b : NetCostMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<NetCostMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NetCostMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NetCostMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NetCostMethodEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_NET_COST_METHOD = "netCostMethod";
  @SerializedName(SERIALIZED_NAME_NET_COST_METHOD)
  private NetCostMethodEnum netCostMethod;

  public static final String SERIALIZED_NAME_ORIGIN_COUNTRY_CODE = "originCountryCode";
  @SerializedName(SERIALIZED_NAME_ORIGIN_COUNTRY_CODE)
  private String originCountryCode;

  public static final String SERIALIZED_NAME_ORIGIN_STATE_PROVINCE = "originStateProvince";
  @SerializedName(SERIALIZED_NAME_ORIGIN_STATE_PROVINCE)
  private String originStateProvince;

  /**
   * Gets or Sets preferenceCriterion
   */
  @JsonAdapter(PreferenceCriterionEnum.Adapter.class)
  public enum PreferenceCriterionEnum {
    A("A"),
    
    B("B"),
    
    C("C"),
    
    D("D"),
    
    E("E"),
    
    F("F");

    private String value;

    PreferenceCriterionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PreferenceCriterionEnum fromValue(String value) {
      for (PreferenceCriterionEnum b : PreferenceCriterionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PreferenceCriterionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PreferenceCriterionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PreferenceCriterionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PreferenceCriterionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PREFERENCE_CRITERION = "preferenceCriterion";
  @SerializedName(SERIALIZED_NAME_PREFERENCE_CRITERION)
  private PreferenceCriterionEnum preferenceCriterion;

  public static final String SERIALIZED_NAME_PRODUCER_ADDRESS = "producerAddress";
  @SerializedName(SERIALIZED_NAME_PRODUCER_ADDRESS)
  private Address producerAddress;

  /**
   * Gets or Sets producerDetermination
   */
  @JsonAdapter(ProducerDeterminationEnum.Adapter.class)
  public enum ProducerDeterminationEnum {
    NO_1("NO_1"),
    
    NO_2("NO_2"),
    
    NO_3("NO_3"),
    
    PD_YES("PD_YES");

    private String value;

    ProducerDeterminationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProducerDeterminationEnum fromValue(String value) {
      for (ProducerDeterminationEnum b : ProducerDeterminationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProducerDeterminationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProducerDeterminationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProducerDeterminationEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProducerDeterminationEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PRODUCER_DETERMINATION = "producerDetermination";
  @SerializedName(SERIALIZED_NAME_PRODUCER_DETERMINATION)
  private ProducerDeterminationEnum producerDetermination;

  public static final String SERIALIZED_NAME_PRODUCER_ID = "producerId";
  @SerializedName(SERIALIZED_NAME_PRODUCER_ID)
  private String producerId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_QUANTITY_U_O_M = "quantityUOM";
  @SerializedName(SERIALIZED_NAME_QUANTITY_U_O_M)
  private String quantityUOM;

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unitPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice;

  public static final String SERIALIZED_NAME_UNIT_WEIGHT = "unitWeight";
  @SerializedName(SERIALIZED_NAME_UNIT_WEIGHT)
  private ParcelWeight unitWeight;


  public CustomsItem description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CustomsItem hSTariffCode(String hSTariffCode) {
    
    this.hSTariffCode = hSTariffCode;
    return this;
  }

   /**
   * Get hSTariffCode
   * @return hSTariffCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String gethSTariffCode() {
    return hSTariffCode;
  }


  public void sethSTariffCode(String hSTariffCode) {
    this.hSTariffCode = hSTariffCode;
  }


  public CustomsItem netCostMethod(NetCostMethodEnum netCostMethod) {
    
    this.netCostMethod = netCostMethod;
    return this;
  }

   /**
   * Get netCostMethod
   * @return netCostMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NetCostMethodEnum getNetCostMethod() {
    return netCostMethod;
  }


  public void setNetCostMethod(NetCostMethodEnum netCostMethod) {
    this.netCostMethod = netCostMethod;
  }


  public CustomsItem originCountryCode(String originCountryCode) {
    
    this.originCountryCode = originCountryCode;
    return this;
  }

   /**
   * Get originCountryCode
   * @return originCountryCode
  **/
  @ApiModelProperty(required = true, value = "")

  public String getOriginCountryCode() {
    return originCountryCode;
  }


  public void setOriginCountryCode(String originCountryCode) {
    this.originCountryCode = originCountryCode;
  }


  public CustomsItem originStateProvince(String originStateProvince) {
    
    this.originStateProvince = originStateProvince;
    return this;
  }

   /**
   * Get originStateProvince
   * @return originStateProvince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOriginStateProvince() {
    return originStateProvince;
  }


  public void setOriginStateProvince(String originStateProvince) {
    this.originStateProvince = originStateProvince;
  }


  public CustomsItem preferenceCriterion(PreferenceCriterionEnum preferenceCriterion) {
    
    this.preferenceCriterion = preferenceCriterion;
    return this;
  }

   /**
   * Get preferenceCriterion
   * @return preferenceCriterion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PreferenceCriterionEnum getPreferenceCriterion() {
    return preferenceCriterion;
  }


  public void setPreferenceCriterion(PreferenceCriterionEnum preferenceCriterion) {
    this.preferenceCriterion = preferenceCriterion;
  }


  public CustomsItem producerAddress(Address producerAddress) {
    
    this.producerAddress = producerAddress;
    return this;
  }

   /**
   * Get producerAddress
   * @return producerAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getProducerAddress() {
    return producerAddress;
  }


  public void setProducerAddress(Address producerAddress) {
    this.producerAddress = producerAddress;
  }


  public CustomsItem producerDetermination(ProducerDeterminationEnum producerDetermination) {
    
    this.producerDetermination = producerDetermination;
    return this;
  }

   /**
   * Get producerDetermination
   * @return producerDetermination
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProducerDeterminationEnum getProducerDetermination() {
    return producerDetermination;
  }


  public void setProducerDetermination(ProducerDeterminationEnum producerDetermination) {
    this.producerDetermination = producerDetermination;
  }


  public CustomsItem producerId(String producerId) {
    
    this.producerId = producerId;
    return this;
  }

   /**
   * Get producerId
   * @return producerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProducerId() {
    return producerId;
  }


  public void setProducerId(String producerId) {
    this.producerId = producerId;
  }


  public CustomsItem quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public CustomsItem quantityUOM(String quantityUOM) {
    
    this.quantityUOM = quantityUOM;
    return this;
  }

   /**
   * Get quantityUOM
   * @return quantityUOM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQuantityUOM() {
    return quantityUOM;
  }


  public void setQuantityUOM(String quantityUOM) {
    this.quantityUOM = quantityUOM;
  }


  public CustomsItem unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  public CustomsItem unitWeight(ParcelWeight unitWeight) {
    
    this.unitWeight = unitWeight;
    return this;
  }

   /**
   * Get unitWeight
   * @return unitWeight
  **/
  @ApiModelProperty(required = true, value = "")

  public ParcelWeight getUnitWeight() {
    return unitWeight;
  }


  public void setUnitWeight(ParcelWeight unitWeight) {
    this.unitWeight = unitWeight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomsItem customsItem = (CustomsItem) o;
    return Objects.equals(this.description, customsItem.description) &&
        Objects.equals(this.hSTariffCode, customsItem.hSTariffCode) &&
        Objects.equals(this.netCostMethod, customsItem.netCostMethod) &&
        Objects.equals(this.originCountryCode, customsItem.originCountryCode) &&
        Objects.equals(this.originStateProvince, customsItem.originStateProvince) &&
        Objects.equals(this.preferenceCriterion, customsItem.preferenceCriterion) &&
        Objects.equals(this.producerAddress, customsItem.producerAddress) &&
        Objects.equals(this.producerDetermination, customsItem.producerDetermination) &&
        Objects.equals(this.producerId, customsItem.producerId) &&
        Objects.equals(this.quantity, customsItem.quantity) &&
        Objects.equals(this.quantityUOM, customsItem.quantityUOM) &&
        Objects.equals(this.unitPrice, customsItem.unitPrice) &&
        Objects.equals(this.unitWeight, customsItem.unitWeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, hSTariffCode, netCostMethod, originCountryCode, originStateProvince, preferenceCriterion, producerAddress, producerDetermination, producerId, quantity, quantityUOM, unitPrice, unitWeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomsItem {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hSTariffCode: ").append(toIndentedString(hSTariffCode)).append("\n");
    sb.append("    netCostMethod: ").append(toIndentedString(netCostMethod)).append("\n");
    sb.append("    originCountryCode: ").append(toIndentedString(originCountryCode)).append("\n");
    sb.append("    originStateProvince: ").append(toIndentedString(originStateProvince)).append("\n");
    sb.append("    preferenceCriterion: ").append(toIndentedString(preferenceCriterion)).append("\n");
    sb.append("    producerAddress: ").append(toIndentedString(producerAddress)).append("\n");
    sb.append("    producerDetermination: ").append(toIndentedString(producerDetermination)).append("\n");
    sb.append("    producerId: ").append(toIndentedString(producerId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    quantityUOM: ").append(toIndentedString(quantityUOM)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    unitWeight: ").append(toIndentedString(unitWeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

