/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.DimensionRules;
import org.openapitools.client.model.ParcelType;
import org.openapitools.client.model.SpecialServiceCodes;
import org.openapitools.client.model.SpecialServicesRule;
import org.openapitools.client.model.Trackable;
import org.openapitools.client.model.WeightRules;

/**
 * ParcelTypeRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class ParcelTypeRules {
  public static final String SERIALIZED_NAME_PARCEL_TYPE = "parcelType";
  @SerializedName(SERIALIZED_NAME_PARCEL_TYPE)
  private ParcelType parcelType;

  public static final String SERIALIZED_NAME_BRANDED_NAME = "brandedName";
  @SerializedName(SERIALIZED_NAME_BRANDED_NAME)
  private String brandedName;

  public static final String SERIALIZED_NAME_RATE_TYPE_ID = "rateTypeId";
  @SerializedName(SERIALIZED_NAME_RATE_TYPE_ID)
  private String rateTypeId;

  public static final String SERIALIZED_NAME_RATE_TYPE_BRANDED_NAME = "rateTypeBrandedName";
  @SerializedName(SERIALIZED_NAME_RATE_TYPE_BRANDED_NAME)
  private String rateTypeBrandedName;

  public static final String SERIALIZED_NAME_TRACKABLE = "trackable";
  @SerializedName(SERIALIZED_NAME_TRACKABLE)
  private Trackable trackable = Trackable.TRACKABLE;

  public static final String SERIALIZED_NAME_SPECIAL_SERVICES_RULE = "specialServicesRule";
  @SerializedName(SERIALIZED_NAME_SPECIAL_SERVICES_RULE)
  private List<SpecialServicesRule> specialServicesRule = null;

  public static final String SERIALIZED_NAME_WEIGHT_RULES = "weightRules";
  @SerializedName(SERIALIZED_NAME_WEIGHT_RULES)
  private List<WeightRules> weightRules = null;

  public static final String SERIALIZED_NAME_DIMENSION_RULES = "dimensionRules";
  @SerializedName(SERIALIZED_NAME_DIMENSION_RULES)
  private List<DimensionRules> dimensionRules = null;

  public static final String SERIALIZED_NAME_SUGGESTED_TRACKABLE_SPECIAL_SERVICE_ID = "suggestedTrackableSpecialServiceId";
  @SerializedName(SERIALIZED_NAME_SUGGESTED_TRACKABLE_SPECIAL_SERVICE_ID)
  private SpecialServiceCodes suggestedTrackableSpecialServiceId;


  public ParcelTypeRules parcelType(ParcelType parcelType) {
    
    this.parcelType = parcelType;
    return this;
  }

   /**
   * Get parcelType
   * @return parcelType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelType getParcelType() {
    return parcelType;
  }


  public void setParcelType(ParcelType parcelType) {
    this.parcelType = parcelType;
  }


  public ParcelTypeRules brandedName(String brandedName) {
    
    this.brandedName = brandedName;
    return this;
  }

   /**
   * Get brandedName
   * @return brandedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrandedName() {
    return brandedName;
  }


  public void setBrandedName(String brandedName) {
    this.brandedName = brandedName;
  }


  public ParcelTypeRules rateTypeId(String rateTypeId) {
    
    this.rateTypeId = rateTypeId;
    return this;
  }

   /**
   * Get rateTypeId
   * @return rateTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRateTypeId() {
    return rateTypeId;
  }


  public void setRateTypeId(String rateTypeId) {
    this.rateTypeId = rateTypeId;
  }


  public ParcelTypeRules rateTypeBrandedName(String rateTypeBrandedName) {
    
    this.rateTypeBrandedName = rateTypeBrandedName;
    return this;
  }

   /**
   * Get rateTypeBrandedName
   * @return rateTypeBrandedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRateTypeBrandedName() {
    return rateTypeBrandedName;
  }


  public void setRateTypeBrandedName(String rateTypeBrandedName) {
    this.rateTypeBrandedName = rateTypeBrandedName;
  }


  public ParcelTypeRules trackable(Trackable trackable) {
    
    this.trackable = trackable;
    return this;
  }

   /**
   * Get trackable
   * @return trackable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Trackable getTrackable() {
    return trackable;
  }


  public void setTrackable(Trackable trackable) {
    this.trackable = trackable;
  }


  public ParcelTypeRules specialServicesRule(List<SpecialServicesRule> specialServicesRule) {
    
    this.specialServicesRule = specialServicesRule;
    return this;
  }

  public ParcelTypeRules addSpecialServicesRuleItem(SpecialServicesRule specialServicesRuleItem) {
    if (this.specialServicesRule == null) {
      this.specialServicesRule = new ArrayList<SpecialServicesRule>();
    }
    this.specialServicesRule.add(specialServicesRuleItem);
    return this;
  }

   /**
   * Get specialServicesRule
   * @return specialServicesRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SpecialServicesRule> getSpecialServicesRule() {
    return specialServicesRule;
  }


  public void setSpecialServicesRule(List<SpecialServicesRule> specialServicesRule) {
    this.specialServicesRule = specialServicesRule;
  }


  public ParcelTypeRules weightRules(List<WeightRules> weightRules) {
    
    this.weightRules = weightRules;
    return this;
  }

  public ParcelTypeRules addWeightRulesItem(WeightRules weightRulesItem) {
    if (this.weightRules == null) {
      this.weightRules = new ArrayList<WeightRules>();
    }
    this.weightRules.add(weightRulesItem);
    return this;
  }

   /**
   * Get weightRules
   * @return weightRules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WeightRules> getWeightRules() {
    return weightRules;
  }


  public void setWeightRules(List<WeightRules> weightRules) {
    this.weightRules = weightRules;
  }


  public ParcelTypeRules dimensionRules(List<DimensionRules> dimensionRules) {
    
    this.dimensionRules = dimensionRules;
    return this;
  }

  public ParcelTypeRules addDimensionRulesItem(DimensionRules dimensionRulesItem) {
    if (this.dimensionRules == null) {
      this.dimensionRules = new ArrayList<DimensionRules>();
    }
    this.dimensionRules.add(dimensionRulesItem);
    return this;
  }

   /**
   * Get dimensionRules
   * @return dimensionRules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DimensionRules> getDimensionRules() {
    return dimensionRules;
  }


  public void setDimensionRules(List<DimensionRules> dimensionRules) {
    this.dimensionRules = dimensionRules;
  }


  public ParcelTypeRules suggestedTrackableSpecialServiceId(SpecialServiceCodes suggestedTrackableSpecialServiceId) {
    
    this.suggestedTrackableSpecialServiceId = suggestedTrackableSpecialServiceId;
    return this;
  }

   /**
   * Get suggestedTrackableSpecialServiceId
   * @return suggestedTrackableSpecialServiceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SpecialServiceCodes getSuggestedTrackableSpecialServiceId() {
    return suggestedTrackableSpecialServiceId;
  }


  public void setSuggestedTrackableSpecialServiceId(SpecialServiceCodes suggestedTrackableSpecialServiceId) {
    this.suggestedTrackableSpecialServiceId = suggestedTrackableSpecialServiceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelTypeRules parcelTypeRules = (ParcelTypeRules) o;
    return Objects.equals(this.parcelType, parcelTypeRules.parcelType) &&
        Objects.equals(this.brandedName, parcelTypeRules.brandedName) &&
        Objects.equals(this.rateTypeId, parcelTypeRules.rateTypeId) &&
        Objects.equals(this.rateTypeBrandedName, parcelTypeRules.rateTypeBrandedName) &&
        Objects.equals(this.trackable, parcelTypeRules.trackable) &&
        Objects.equals(this.specialServicesRule, parcelTypeRules.specialServicesRule) &&
        Objects.equals(this.weightRules, parcelTypeRules.weightRules) &&
        Objects.equals(this.dimensionRules, parcelTypeRules.dimensionRules) &&
        Objects.equals(this.suggestedTrackableSpecialServiceId, parcelTypeRules.suggestedTrackableSpecialServiceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parcelType, brandedName, rateTypeId, rateTypeBrandedName, trackable, specialServicesRule, weightRules, dimensionRules, suggestedTrackableSpecialServiceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelTypeRules {\n");
    sb.append("    parcelType: ").append(toIndentedString(parcelType)).append("\n");
    sb.append("    brandedName: ").append(toIndentedString(brandedName)).append("\n");
    sb.append("    rateTypeId: ").append(toIndentedString(rateTypeId)).append("\n");
    sb.append("    rateTypeBrandedName: ").append(toIndentedString(rateTypeBrandedName)).append("\n");
    sb.append("    trackable: ").append(toIndentedString(trackable)).append("\n");
    sb.append("    specialServicesRule: ").append(toIndentedString(specialServicesRule)).append("\n");
    sb.append("    weightRules: ").append(toIndentedString(weightRules)).append("\n");
    sb.append("    dimensionRules: ").append(toIndentedString(dimensionRules)).append("\n");
    sb.append("    suggestedTrackableSpecialServiceId: ").append(toIndentedString(suggestedTrackableSpecialServiceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

