/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ParcelProtectionCreateRequestShipmentInfoConsigneeInfo;
import org.openapitools.client.model.ParcelProtectionCreateRequestShipmentInfoParcelInfo;
import org.openapitools.client.model.ParcelProtectionCreateRequestShipmentInfoShipperInfo;

/**
 * ParcelProtectionCreateRequestShipmentInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-17T23:33:31.071+05:30[Asia/Calcutta]")
public class ParcelProtectionCreateRequestShipmentInfo {
  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "trackingNumber";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  private String trackingNumber;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private String carrier;

  public static final String SERIALIZED_NAME_SERVICE_ID = "serviceId";
  @SerializedName(SERIALIZED_NAME_SERVICE_ID)
  private String serviceId;

  public static final String SERIALIZED_NAME_INSURANCE_COVERAGE_VALUE = "insuranceCoverageValue";
  @SerializedName(SERIALIZED_NAME_INSURANCE_COVERAGE_VALUE)
  private Integer insuranceCoverageValue;

  public static final String SERIALIZED_NAME_INSURANCE_COVERAGE_VALUE_CURRENCY = "insuranceCoverageValueCurrency";
  @SerializedName(SERIALIZED_NAME_INSURANCE_COVERAGE_VALUE_CURRENCY)
  private String insuranceCoverageValueCurrency;

  public static final String SERIALIZED_NAME_PARCEL_INFO = "parcelInfo";
  @SerializedName(SERIALIZED_NAME_PARCEL_INFO)
  private ParcelProtectionCreateRequestShipmentInfoParcelInfo parcelInfo;

  public static final String SERIALIZED_NAME_SHIPPER_INFO = "shipperInfo";
  @SerializedName(SERIALIZED_NAME_SHIPPER_INFO)
  private ParcelProtectionCreateRequestShipmentInfoShipperInfo shipperInfo;

  public static final String SERIALIZED_NAME_CONSIGNEE_INFO = "consigneeInfo";
  @SerializedName(SERIALIZED_NAME_CONSIGNEE_INFO)
  private ParcelProtectionCreateRequestShipmentInfoConsigneeInfo consigneeInfo;


  public ParcelProtectionCreateRequestShipmentInfo trackingNumber(String trackingNumber) {
    
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * Get trackingNumber
   * @return trackingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTrackingNumber() {
    return trackingNumber;
  }


  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public ParcelProtectionCreateRequestShipmentInfo carrier(String carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarrier() {
    return carrier;
  }


  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }


  public ParcelProtectionCreateRequestShipmentInfo serviceId(String serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceId() {
    return serviceId;
  }


  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }


  public ParcelProtectionCreateRequestShipmentInfo insuranceCoverageValue(Integer insuranceCoverageValue) {
    
    this.insuranceCoverageValue = insuranceCoverageValue;
    return this;
  }

   /**
   * Get insuranceCoverageValue
   * @return insuranceCoverageValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getInsuranceCoverageValue() {
    return insuranceCoverageValue;
  }


  public void setInsuranceCoverageValue(Integer insuranceCoverageValue) {
    this.insuranceCoverageValue = insuranceCoverageValue;
  }


  public ParcelProtectionCreateRequestShipmentInfo insuranceCoverageValueCurrency(String insuranceCoverageValueCurrency) {
    
    this.insuranceCoverageValueCurrency = insuranceCoverageValueCurrency;
    return this;
  }

   /**
   * Get insuranceCoverageValueCurrency
   * @return insuranceCoverageValueCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInsuranceCoverageValueCurrency() {
    return insuranceCoverageValueCurrency;
  }


  public void setInsuranceCoverageValueCurrency(String insuranceCoverageValueCurrency) {
    this.insuranceCoverageValueCurrency = insuranceCoverageValueCurrency;
  }


  public ParcelProtectionCreateRequestShipmentInfo parcelInfo(ParcelProtectionCreateRequestShipmentInfoParcelInfo parcelInfo) {
    
    this.parcelInfo = parcelInfo;
    return this;
  }

   /**
   * Get parcelInfo
   * @return parcelInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelProtectionCreateRequestShipmentInfoParcelInfo getParcelInfo() {
    return parcelInfo;
  }


  public void setParcelInfo(ParcelProtectionCreateRequestShipmentInfoParcelInfo parcelInfo) {
    this.parcelInfo = parcelInfo;
  }


  public ParcelProtectionCreateRequestShipmentInfo shipperInfo(ParcelProtectionCreateRequestShipmentInfoShipperInfo shipperInfo) {
    
    this.shipperInfo = shipperInfo;
    return this;
  }

   /**
   * Get shipperInfo
   * @return shipperInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelProtectionCreateRequestShipmentInfoShipperInfo getShipperInfo() {
    return shipperInfo;
  }


  public void setShipperInfo(ParcelProtectionCreateRequestShipmentInfoShipperInfo shipperInfo) {
    this.shipperInfo = shipperInfo;
  }


  public ParcelProtectionCreateRequestShipmentInfo consigneeInfo(ParcelProtectionCreateRequestShipmentInfoConsigneeInfo consigneeInfo) {
    
    this.consigneeInfo = consigneeInfo;
    return this;
  }

   /**
   * Get consigneeInfo
   * @return consigneeInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelProtectionCreateRequestShipmentInfoConsigneeInfo getConsigneeInfo() {
    return consigneeInfo;
  }


  public void setConsigneeInfo(ParcelProtectionCreateRequestShipmentInfoConsigneeInfo consigneeInfo) {
    this.consigneeInfo = consigneeInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelProtectionCreateRequestShipmentInfo parcelProtectionCreateRequestShipmentInfo = (ParcelProtectionCreateRequestShipmentInfo) o;
    return Objects.equals(this.trackingNumber, parcelProtectionCreateRequestShipmentInfo.trackingNumber) &&
        Objects.equals(this.carrier, parcelProtectionCreateRequestShipmentInfo.carrier) &&
        Objects.equals(this.serviceId, parcelProtectionCreateRequestShipmentInfo.serviceId) &&
        Objects.equals(this.insuranceCoverageValue, parcelProtectionCreateRequestShipmentInfo.insuranceCoverageValue) &&
        Objects.equals(this.insuranceCoverageValueCurrency, parcelProtectionCreateRequestShipmentInfo.insuranceCoverageValueCurrency) &&
        Objects.equals(this.parcelInfo, parcelProtectionCreateRequestShipmentInfo.parcelInfo) &&
        Objects.equals(this.shipperInfo, parcelProtectionCreateRequestShipmentInfo.shipperInfo) &&
        Objects.equals(this.consigneeInfo, parcelProtectionCreateRequestShipmentInfo.consigneeInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackingNumber, carrier, serviceId, insuranceCoverageValue, insuranceCoverageValueCurrency, parcelInfo, shipperInfo, consigneeInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelProtectionCreateRequestShipmentInfo {\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    insuranceCoverageValue: ").append(toIndentedString(insuranceCoverageValue)).append("\n");
    sb.append("    insuranceCoverageValueCurrency: ").append(toIndentedString(insuranceCoverageValueCurrency)).append("\n");
    sb.append("    parcelInfo: ").append(toIndentedString(parcelInfo)).append("\n");
    sb.append("    shipperInfo: ").append(toIndentedString(shipperInfo)).append("\n");
    sb.append("    consigneeInfo: ").append(toIndentedString(consigneeInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

