/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Carrier;
import org.openapitools.client.model.DeliveryCommitment;
import org.openapitools.client.model.Discount;
import org.openapitools.client.model.ParcelType;
import org.openapitools.client.model.ParcelWeight;
import org.openapitools.client.model.Services;
import org.openapitools.client.model.SpecialService;
import org.openapitools.client.model.Surcharge;
import org.openapitools.client.model.Tax;

/**
 * Rate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-17T23:33:31.071+05:30[Asia/Calcutta]")
public class Rate {
  public static final String SERIALIZED_NAME_ALTERNATE_BASE_CHARGE = "alternateBaseCharge";
  @SerializedName(SERIALIZED_NAME_ALTERNATE_BASE_CHARGE)
  private BigDecimal alternateBaseCharge;

  public static final String SERIALIZED_NAME_ALTERNATE_TOTAL_CHARGE = "alternateTotalCharge";
  @SerializedName(SERIALIZED_NAME_ALTERNATE_TOTAL_CHARGE)
  private BigDecimal alternateTotalCharge;

  public static final String SERIALIZED_NAME_BASE_CHARGE = "baseCharge";
  @SerializedName(SERIALIZED_NAME_BASE_CHARGE)
  private BigDecimal baseCharge;

  public static final String SERIALIZED_NAME_BASE_CHARGE_TAXES = "baseChargeTaxes";
  @SerializedName(SERIALIZED_NAME_BASE_CHARGE_TAXES)
  private List<Tax> baseChargeTaxes = null;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private Carrier carrier = Carrier.USPS;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currencyCode";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_DELIVERY_COMMITMENT = "deliveryCommitment";
  @SerializedName(SERIALIZED_NAME_DELIVERY_COMMITMENT)
  private DeliveryCommitment deliveryCommitment;

  public static final String SERIALIZED_NAME_DESTINATION_ZONE = "destinationZone";
  @SerializedName(SERIALIZED_NAME_DESTINATION_ZONE)
  private BigDecimal destinationZone;

  public static final String SERIALIZED_NAME_DIMENSIONAL_WEIGHT = "dimensionalWeight";
  @SerializedName(SERIALIZED_NAME_DIMENSIONAL_WEIGHT)
  private ParcelWeight dimensionalWeight;

  public static final String SERIALIZED_NAME_DISCOUNTS = "discounts";
  @SerializedName(SERIALIZED_NAME_DISCOUNTS)
  private List<Discount> discounts = null;

  public static final String SERIALIZED_NAME_INDUCTION_POSTAL_CODE = "inductionPostalCode";
  @SerializedName(SERIALIZED_NAME_INDUCTION_POSTAL_CODE)
  private String inductionPostalCode;

  public static final String SERIALIZED_NAME_PARCEL_TYPE = "parcelType";
  @SerializedName(SERIALIZED_NAME_PARCEL_TYPE)
  private ParcelType parcelType;

  public static final String SERIALIZED_NAME_RATE_TYPE_ID = "rateTypeId";
  @SerializedName(SERIALIZED_NAME_RATE_TYPE_ID)
  private String rateTypeId;

  public static final String SERIALIZED_NAME_SERVICE_ID = "serviceId";
  @SerializedName(SERIALIZED_NAME_SERVICE_ID)
  private Services serviceId;

  public static final String SERIALIZED_NAME_SPECIAL_SERVICES = "specialServices";
  @SerializedName(SERIALIZED_NAME_SPECIAL_SERVICES)
  private List<SpecialService> specialServices = null;

  public static final String SERIALIZED_NAME_SURCHARGES = "surcharges";
  @SerializedName(SERIALIZED_NAME_SURCHARGES)
  private List<Surcharge> surcharges = null;

  public static final String SERIALIZED_NAME_TOTAL_CARRIER_CHARGE = "totalCarrierCharge";
  @SerializedName(SERIALIZED_NAME_TOTAL_CARRIER_CHARGE)
  private BigDecimal totalCarrierCharge;

  public static final String SERIALIZED_NAME_TOTAL_TAX_AMOUNT = "totalTaxAmount";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX_AMOUNT)
  private BigDecimal totalTaxAmount;


  public Rate alternateBaseCharge(BigDecimal alternateBaseCharge) {
    
    this.alternateBaseCharge = alternateBaseCharge;
    return this;
  }

   /**
   * Get alternateBaseCharge
   * @return alternateBaseCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAlternateBaseCharge() {
    return alternateBaseCharge;
  }


  public void setAlternateBaseCharge(BigDecimal alternateBaseCharge) {
    this.alternateBaseCharge = alternateBaseCharge;
  }


  public Rate alternateTotalCharge(BigDecimal alternateTotalCharge) {
    
    this.alternateTotalCharge = alternateTotalCharge;
    return this;
  }

   /**
   * Get alternateTotalCharge
   * @return alternateTotalCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAlternateTotalCharge() {
    return alternateTotalCharge;
  }


  public void setAlternateTotalCharge(BigDecimal alternateTotalCharge) {
    this.alternateTotalCharge = alternateTotalCharge;
  }


  public Rate baseCharge(BigDecimal baseCharge) {
    
    this.baseCharge = baseCharge;
    return this;
  }

   /**
   * Get baseCharge
   * @return baseCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBaseCharge() {
    return baseCharge;
  }


  public void setBaseCharge(BigDecimal baseCharge) {
    this.baseCharge = baseCharge;
  }


  public Rate baseChargeTaxes(List<Tax> baseChargeTaxes) {
    
    this.baseChargeTaxes = baseChargeTaxes;
    return this;
  }

  public Rate addBaseChargeTaxesItem(Tax baseChargeTaxesItem) {
    if (this.baseChargeTaxes == null) {
      this.baseChargeTaxes = new ArrayList<Tax>();
    }
    this.baseChargeTaxes.add(baseChargeTaxesItem);
    return this;
  }

   /**
   * Get baseChargeTaxes
   * @return baseChargeTaxes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Tax> getBaseChargeTaxes() {
    return baseChargeTaxes;
  }


  public void setBaseChargeTaxes(List<Tax> baseChargeTaxes) {
    this.baseChargeTaxes = baseChargeTaxes;
  }


  public Rate carrier(Carrier carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @ApiModelProperty(required = true, value = "")

  public Carrier getCarrier() {
    return carrier;
  }


  public void setCarrier(Carrier carrier) {
    this.carrier = carrier;
  }


  public Rate currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * ISO-4217
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ISO-4217")

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public Rate deliveryCommitment(DeliveryCommitment deliveryCommitment) {
    
    this.deliveryCommitment = deliveryCommitment;
    return this;
  }

   /**
   * Get deliveryCommitment
   * @return deliveryCommitment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeliveryCommitment getDeliveryCommitment() {
    return deliveryCommitment;
  }


  public void setDeliveryCommitment(DeliveryCommitment deliveryCommitment) {
    this.deliveryCommitment = deliveryCommitment;
  }


  public Rate destinationZone(BigDecimal destinationZone) {
    
    this.destinationZone = destinationZone;
    return this;
  }

   /**
   * Get destinationZone
   * @return destinationZone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getDestinationZone() {
    return destinationZone;
  }


  public void setDestinationZone(BigDecimal destinationZone) {
    this.destinationZone = destinationZone;
  }


  public Rate dimensionalWeight(ParcelWeight dimensionalWeight) {
    
    this.dimensionalWeight = dimensionalWeight;
    return this;
  }

   /**
   * Get dimensionalWeight
   * @return dimensionalWeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParcelWeight getDimensionalWeight() {
    return dimensionalWeight;
  }


  public void setDimensionalWeight(ParcelWeight dimensionalWeight) {
    this.dimensionalWeight = dimensionalWeight;
  }


  public Rate discounts(List<Discount> discounts) {
    
    this.discounts = discounts;
    return this;
  }

  public Rate addDiscountsItem(Discount discountsItem) {
    if (this.discounts == null) {
      this.discounts = new ArrayList<Discount>();
    }
    this.discounts.add(discountsItem);
    return this;
  }

   /**
   * Get discounts
   * @return discounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Discount> getDiscounts() {
    return discounts;
  }


  public void setDiscounts(List<Discount> discounts) {
    this.discounts = discounts;
  }


  public Rate inductionPostalCode(String inductionPostalCode) {
    
    this.inductionPostalCode = inductionPostalCode;
    return this;
  }

   /**
   * Get inductionPostalCode
   * @return inductionPostalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInductionPostalCode() {
    return inductionPostalCode;
  }


  public void setInductionPostalCode(String inductionPostalCode) {
    this.inductionPostalCode = inductionPostalCode;
  }


  public Rate parcelType(ParcelType parcelType) {
    
    this.parcelType = parcelType;
    return this;
  }

   /**
   * Get parcelType
   * @return parcelType
  **/
  @ApiModelProperty(required = true, value = "")

  public ParcelType getParcelType() {
    return parcelType;
  }


  public void setParcelType(ParcelType parcelType) {
    this.parcelType = parcelType;
  }


  public Rate rateTypeId(String rateTypeId) {
    
    this.rateTypeId = rateTypeId;
    return this;
  }

   /**
   * Get rateTypeId
   * @return rateTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRateTypeId() {
    return rateTypeId;
  }


  public void setRateTypeId(String rateTypeId) {
    this.rateTypeId = rateTypeId;
  }


  public Rate serviceId(Services serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Services getServiceId() {
    return serviceId;
  }


  public void setServiceId(Services serviceId) {
    this.serviceId = serviceId;
  }


  public Rate specialServices(List<SpecialService> specialServices) {
    
    this.specialServices = specialServices;
    return this;
  }

  public Rate addSpecialServicesItem(SpecialService specialServicesItem) {
    if (this.specialServices == null) {
      this.specialServices = new ArrayList<SpecialService>();
    }
    this.specialServices.add(specialServicesItem);
    return this;
  }

   /**
   * Get specialServices
   * @return specialServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SpecialService> getSpecialServices() {
    return specialServices;
  }


  public void setSpecialServices(List<SpecialService> specialServices) {
    this.specialServices = specialServices;
  }


  public Rate surcharges(List<Surcharge> surcharges) {
    
    this.surcharges = surcharges;
    return this;
  }

  public Rate addSurchargesItem(Surcharge surchargesItem) {
    if (this.surcharges == null) {
      this.surcharges = new ArrayList<Surcharge>();
    }
    this.surcharges.add(surchargesItem);
    return this;
  }

   /**
   * Get surcharges
   * @return surcharges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Surcharge> getSurcharges() {
    return surcharges;
  }


  public void setSurcharges(List<Surcharge> surcharges) {
    this.surcharges = surcharges;
  }


  public Rate totalCarrierCharge(BigDecimal totalCarrierCharge) {
    
    this.totalCarrierCharge = totalCarrierCharge;
    return this;
  }

   /**
   * Get totalCarrierCharge
   * @return totalCarrierCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalCarrierCharge() {
    return totalCarrierCharge;
  }


  public void setTotalCarrierCharge(BigDecimal totalCarrierCharge) {
    this.totalCarrierCharge = totalCarrierCharge;
  }


  public Rate totalTaxAmount(BigDecimal totalTaxAmount) {
    
    this.totalTaxAmount = totalTaxAmount;
    return this;
  }

   /**
   * Get totalTaxAmount
   * @return totalTaxAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalTaxAmount() {
    return totalTaxAmount;
  }


  public void setTotalTaxAmount(BigDecimal totalTaxAmount) {
    this.totalTaxAmount = totalTaxAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rate rate = (Rate) o;
    return Objects.equals(this.alternateBaseCharge, rate.alternateBaseCharge) &&
        Objects.equals(this.alternateTotalCharge, rate.alternateTotalCharge) &&
        Objects.equals(this.baseCharge, rate.baseCharge) &&
        Objects.equals(this.baseChargeTaxes, rate.baseChargeTaxes) &&
        Objects.equals(this.carrier, rate.carrier) &&
        Objects.equals(this.currencyCode, rate.currencyCode) &&
        Objects.equals(this.deliveryCommitment, rate.deliveryCommitment) &&
        Objects.equals(this.destinationZone, rate.destinationZone) &&
        Objects.equals(this.dimensionalWeight, rate.dimensionalWeight) &&
        Objects.equals(this.discounts, rate.discounts) &&
        Objects.equals(this.inductionPostalCode, rate.inductionPostalCode) &&
        Objects.equals(this.parcelType, rate.parcelType) &&
        Objects.equals(this.rateTypeId, rate.rateTypeId) &&
        Objects.equals(this.serviceId, rate.serviceId) &&
        Objects.equals(this.specialServices, rate.specialServices) &&
        Objects.equals(this.surcharges, rate.surcharges) &&
        Objects.equals(this.totalCarrierCharge, rate.totalCarrierCharge) &&
        Objects.equals(this.totalTaxAmount, rate.totalTaxAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternateBaseCharge, alternateTotalCharge, baseCharge, baseChargeTaxes, carrier, currencyCode, deliveryCommitment, destinationZone, dimensionalWeight, discounts, inductionPostalCode, parcelType, rateTypeId, serviceId, specialServices, surcharges, totalCarrierCharge, totalTaxAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rate {\n");
    sb.append("    alternateBaseCharge: ").append(toIndentedString(alternateBaseCharge)).append("\n");
    sb.append("    alternateTotalCharge: ").append(toIndentedString(alternateTotalCharge)).append("\n");
    sb.append("    baseCharge: ").append(toIndentedString(baseCharge)).append("\n");
    sb.append("    baseChargeTaxes: ").append(toIndentedString(baseChargeTaxes)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    deliveryCommitment: ").append(toIndentedString(deliveryCommitment)).append("\n");
    sb.append("    destinationZone: ").append(toIndentedString(destinationZone)).append("\n");
    sb.append("    dimensionalWeight: ").append(toIndentedString(dimensionalWeight)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("    inductionPostalCode: ").append(toIndentedString(inductionPostalCode)).append("\n");
    sb.append("    parcelType: ").append(toIndentedString(parcelType)).append("\n");
    sb.append("    rateTypeId: ").append(toIndentedString(rateTypeId)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    specialServices: ").append(toIndentedString(specialServices)).append("\n");
    sb.append("    surcharges: ").append(toIndentedString(surcharges)).append("\n");
    sb.append("    totalCarrierCharge: ").append(toIndentedString(totalCarrierCharge)).append("\n");
    sb.append("    totalTaxAmount: ").append(toIndentedString(totalTaxAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

