/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.SchedulePickupPickupSummary;

/**
 * SchedulePickup
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class SchedulePickup {
  public static final String SERIALIZED_NAME_PICKUP_ADDRESS = "pickupAddress";
  @SerializedName(SERIALIZED_NAME_PICKUP_ADDRESS)
  private Address pickupAddress;

  public static final String SERIALIZED_NAME_CARRIER = "carrier";
  @SerializedName(SERIALIZED_NAME_CARRIER)
  private String carrier;

  public static final String SERIALIZED_NAME_PICKUP_SUMMARY = "pickupSummary";
  @SerializedName(SERIALIZED_NAME_PICKUP_SUMMARY)
  private List<SchedulePickupPickupSummary> pickupSummary = null;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_PACKAGE_LOCATION = "packageLocation";
  @SerializedName(SERIALIZED_NAME_PACKAGE_LOCATION)
  private String packageLocation;

  public static final String SERIALIZED_NAME_SPECIAL_INSTRUCTIONS = "specialInstructions";
  @SerializedName(SERIALIZED_NAME_SPECIAL_INSTRUCTIONS)
  private String specialInstructions;


  public SchedulePickup pickupAddress(Address pickupAddress) {
    
    this.pickupAddress = pickupAddress;
    return this;
  }

   /**
   * Get pickupAddress
   * @return pickupAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getPickupAddress() {
    return pickupAddress;
  }


  public void setPickupAddress(Address pickupAddress) {
    this.pickupAddress = pickupAddress;
  }


  public SchedulePickup carrier(String carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarrier() {
    return carrier;
  }


  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }


  public SchedulePickup pickupSummary(List<SchedulePickupPickupSummary> pickupSummary) {
    
    this.pickupSummary = pickupSummary;
    return this;
  }

  public SchedulePickup addPickupSummaryItem(SchedulePickupPickupSummary pickupSummaryItem) {
    if (this.pickupSummary == null) {
      this.pickupSummary = new ArrayList<SchedulePickupPickupSummary>();
    }
    this.pickupSummary.add(pickupSummaryItem);
    return this;
  }

   /**
   * Get pickupSummary
   * @return pickupSummary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SchedulePickupPickupSummary> getPickupSummary() {
    return pickupSummary;
  }


  public void setPickupSummary(List<SchedulePickupPickupSummary> pickupSummary) {
    this.pickupSummary = pickupSummary;
  }


  public SchedulePickup reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    this.reference = reference;
  }


  public SchedulePickup packageLocation(String packageLocation) {
    
    this.packageLocation = packageLocation;
    return this;
  }

   /**
   * Get packageLocation
   * @return packageLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackageLocation() {
    return packageLocation;
  }


  public void setPackageLocation(String packageLocation) {
    this.packageLocation = packageLocation;
  }


  public SchedulePickup specialInstructions(String specialInstructions) {
    
    this.specialInstructions = specialInstructions;
    return this;
  }

   /**
   * Get specialInstructions
   * @return specialInstructions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSpecialInstructions() {
    return specialInstructions;
  }


  public void setSpecialInstructions(String specialInstructions) {
    this.specialInstructions = specialInstructions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchedulePickup schedulePickup = (SchedulePickup) o;
    return Objects.equals(this.pickupAddress, schedulePickup.pickupAddress) &&
        Objects.equals(this.carrier, schedulePickup.carrier) &&
        Objects.equals(this.pickupSummary, schedulePickup.pickupSummary) &&
        Objects.equals(this.reference, schedulePickup.reference) &&
        Objects.equals(this.packageLocation, schedulePickup.packageLocation) &&
        Objects.equals(this.specialInstructions, schedulePickup.specialInstructions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pickupAddress, carrier, pickupSummary, reference, packageLocation, specialInstructions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchedulePickup {\n");
    sb.append("    pickupAddress: ").append(toIndentedString(pickupAddress)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    pickupSummary: ").append(toIndentedString(pickupSummary)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    packageLocation: ").append(toIndentedString(packageLocation)).append("\n");
    sb.append("    specialInstructions: ").append(toIndentedString(specialInstructions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

