/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AdditionalAddress;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.CarrierPayment;
import org.openapitools.client.model.Customs;
import org.openapitools.client.model.Document;
import org.openapitools.client.model.HazmatDetails;
import org.openapitools.client.model.Parameter;
import org.openapitools.client.model.Parcel;
import org.openapitools.client.model.Rate;

/**
 * Shipment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:45:29.729+05:30[Asia/Calcutta]")
public class Shipment {
  public static final String SERIALIZED_NAME_ADDITIONAL_ADDRESSES = "additionalAddresses";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_ADDRESSES)
  private List<AdditionalAddress> additionalAddresses = null;

  public static final String SERIALIZED_NAME_ALT_RETURN_ADDRESS = "altReturnAddress";
  @SerializedName(SERIALIZED_NAME_ALT_RETURN_ADDRESS)
  private Address altReturnAddress;

  public static final String SERIALIZED_NAME_CARRIER_PAYMENTS = "carrierPayments";
  @SerializedName(SERIALIZED_NAME_CARRIER_PAYMENTS)
  private List<CarrierPayment> carrierPayments = null;

  public static final String SERIALIZED_NAME_CUSTOMS = "customs";
  @SerializedName(SERIALIZED_NAME_CUSTOMS)
  private Customs customs;

  public static final String SERIALIZED_NAME_DOCUMENTS = "documents";
  @SerializedName(SERIALIZED_NAME_DOCUMENTS)
  private List<Document> documents = null;

  public static final String SERIALIZED_NAME_FROM_ADDRESS = "fromAddress";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS)
  private Address fromAddress;

  public static final String SERIALIZED_NAME_HAZMAT_DETAILS = "hazmatDetails";
  @SerializedName(SERIALIZED_NAME_HAZMAT_DETAILS)
  private HazmatDetails hazmatDetails;

  public static final String SERIALIZED_NAME_PARCEL = "parcel";
  @SerializedName(SERIALIZED_NAME_PARCEL)
  private Parcel parcel;

  public static final String SERIALIZED_NAME_PARCEL_TRACKING_NUMBER = "parcelTrackingNumber";
  @SerializedName(SERIALIZED_NAME_PARCEL_TRACKING_NUMBER)
  private String parcelTrackingNumber;

  public static final String SERIALIZED_NAME_RATES = "rates";
  @SerializedName(SERIALIZED_NAME_RATES)
  private List<Rate> rates = new ArrayList<Rate>();

  public static final String SERIALIZED_NAME_REFERENCES = "references";
  @SerializedName(SERIALIZED_NAME_REFERENCES)
  private List<Parameter> references = null;

  public static final String SERIALIZED_NAME_SHIPMENT_ID = "shipmentId";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_ID)
  private String shipmentId;

  public static final String SERIALIZED_NAME_SHIPMENT_OPTIONS = "shipmentOptions";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_OPTIONS)
  private List<Parameter> shipmentOptions = null;

  /**
   * Gets or Sets shipmentType
   */
  @JsonAdapter(ShipmentTypeEnum.Adapter.class)
  public enum ShipmentTypeEnum {
    OUTBOUND("OUTBOUND"),
    
    RETURN("RETURN");

    private String value;

    ShipmentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ShipmentTypeEnum fromValue(String value) {
      for (ShipmentTypeEnum b : ShipmentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ShipmentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ShipmentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ShipmentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ShipmentTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SHIPMENT_TYPE = "shipmentType";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_TYPE)
  private ShipmentTypeEnum shipmentType;

  public static final String SERIALIZED_NAME_SOLD_TO_ADDRESS = "soldToAddress";
  @SerializedName(SERIALIZED_NAME_SOLD_TO_ADDRESS)
  private Address soldToAddress;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "toAddress";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  private Address toAddress;


  public Shipment additionalAddresses(List<AdditionalAddress> additionalAddresses) {
    
    this.additionalAddresses = additionalAddresses;
    return this;
  }

  public Shipment addAdditionalAddressesItem(AdditionalAddress additionalAddressesItem) {
    if (this.additionalAddresses == null) {
      this.additionalAddresses = new ArrayList<AdditionalAddress>();
    }
    this.additionalAddresses.add(additionalAddressesItem);
    return this;
  }

   /**
   * Get additionalAddresses
   * @return additionalAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AdditionalAddress> getAdditionalAddresses() {
    return additionalAddresses;
  }


  public void setAdditionalAddresses(List<AdditionalAddress> additionalAddresses) {
    this.additionalAddresses = additionalAddresses;
  }


  public Shipment altReturnAddress(Address altReturnAddress) {
    
    this.altReturnAddress = altReturnAddress;
    return this;
  }

   /**
   * Get altReturnAddress
   * @return altReturnAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getAltReturnAddress() {
    return altReturnAddress;
  }


  public void setAltReturnAddress(Address altReturnAddress) {
    this.altReturnAddress = altReturnAddress;
  }


  public Shipment carrierPayments(List<CarrierPayment> carrierPayments) {
    
    this.carrierPayments = carrierPayments;
    return this;
  }

  public Shipment addCarrierPaymentsItem(CarrierPayment carrierPaymentsItem) {
    if (this.carrierPayments == null) {
      this.carrierPayments = new ArrayList<CarrierPayment>();
    }
    this.carrierPayments.add(carrierPaymentsItem);
    return this;
  }

   /**
   * Get carrierPayments
   * @return carrierPayments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CarrierPayment> getCarrierPayments() {
    return carrierPayments;
  }


  public void setCarrierPayments(List<CarrierPayment> carrierPayments) {
    this.carrierPayments = carrierPayments;
  }


  public Shipment customs(Customs customs) {
    
    this.customs = customs;
    return this;
  }

   /**
   * Get customs
   * @return customs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Customs getCustoms() {
    return customs;
  }


  public void setCustoms(Customs customs) {
    this.customs = customs;
  }


  public Shipment documents(List<Document> documents) {
    
    this.documents = documents;
    return this;
  }

  public Shipment addDocumentsItem(Document documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<Document>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Document> getDocuments() {
    return documents;
  }


  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }


  public Shipment fromAddress(Address fromAddress) {
    
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * Get fromAddress
   * @return fromAddress
  **/
  @ApiModelProperty(required = true, value = "")

  public Address getFromAddress() {
    return fromAddress;
  }


  public void setFromAddress(Address fromAddress) {
    this.fromAddress = fromAddress;
  }


  public Shipment hazmatDetails(HazmatDetails hazmatDetails) {
    
    this.hazmatDetails = hazmatDetails;
    return this;
  }

   /**
   * Get hazmatDetails
   * @return hazmatDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HazmatDetails getHazmatDetails() {
    return hazmatDetails;
  }


  public void setHazmatDetails(HazmatDetails hazmatDetails) {
    this.hazmatDetails = hazmatDetails;
  }


  public Shipment parcel(Parcel parcel) {
    
    this.parcel = parcel;
    return this;
  }

   /**
   * Get parcel
   * @return parcel
  **/
  @ApiModelProperty(required = true, value = "")

  public Parcel getParcel() {
    return parcel;
  }


  public void setParcel(Parcel parcel) {
    this.parcel = parcel;
  }


  public Shipment parcelTrackingNumber(String parcelTrackingNumber) {
    
    this.parcelTrackingNumber = parcelTrackingNumber;
    return this;
  }

   /**
   * Get parcelTrackingNumber
   * @return parcelTrackingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParcelTrackingNumber() {
    return parcelTrackingNumber;
  }


  public void setParcelTrackingNumber(String parcelTrackingNumber) {
    this.parcelTrackingNumber = parcelTrackingNumber;
  }


  public Shipment rates(List<Rate> rates) {
    
    this.rates = rates;
    return this;
  }

  public Shipment addRatesItem(Rate ratesItem) {
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @ApiModelProperty(required = true, value = "")

  public List<Rate> getRates() {
    return rates;
  }


  public void setRates(List<Rate> rates) {
    this.rates = rates;
  }


  public Shipment references(List<Parameter> references) {
    
    this.references = references;
    return this;
  }

  public Shipment addReferencesItem(Parameter referencesItem) {
    if (this.references == null) {
      this.references = new ArrayList<Parameter>();
    }
    this.references.add(referencesItem);
    return this;
  }

   /**
   * Get references
   * @return references
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Parameter> getReferences() {
    return references;
  }


  public void setReferences(List<Parameter> references) {
    this.references = references;
  }


  public Shipment shipmentId(String shipmentId) {
    
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShipmentId() {
    return shipmentId;
  }


  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }


  public Shipment shipmentOptions(List<Parameter> shipmentOptions) {
    
    this.shipmentOptions = shipmentOptions;
    return this;
  }

  public Shipment addShipmentOptionsItem(Parameter shipmentOptionsItem) {
    if (this.shipmentOptions == null) {
      this.shipmentOptions = new ArrayList<Parameter>();
    }
    this.shipmentOptions.add(shipmentOptionsItem);
    return this;
  }

   /**
   * Get shipmentOptions
   * @return shipmentOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Parameter> getShipmentOptions() {
    return shipmentOptions;
  }


  public void setShipmentOptions(List<Parameter> shipmentOptions) {
    this.shipmentOptions = shipmentOptions;
  }


  public Shipment shipmentType(ShipmentTypeEnum shipmentType) {
    
    this.shipmentType = shipmentType;
    return this;
  }

   /**
   * Get shipmentType
   * @return shipmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ShipmentTypeEnum getShipmentType() {
    return shipmentType;
  }


  public void setShipmentType(ShipmentTypeEnum shipmentType) {
    this.shipmentType = shipmentType;
  }


  public Shipment soldToAddress(Address soldToAddress) {
    
    this.soldToAddress = soldToAddress;
    return this;
  }

   /**
   * Get soldToAddress
   * @return soldToAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getSoldToAddress() {
    return soldToAddress;
  }


  public void setSoldToAddress(Address soldToAddress) {
    this.soldToAddress = soldToAddress;
  }


  public Shipment toAddress(Address toAddress) {
    
    this.toAddress = toAddress;
    return this;
  }

   /**
   * Get toAddress
   * @return toAddress
  **/
  @ApiModelProperty(required = true, value = "")

  public Address getToAddress() {
    return toAddress;
  }


  public void setToAddress(Address toAddress) {
    this.toAddress = toAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shipment shipment = (Shipment) o;
    return Objects.equals(this.additionalAddresses, shipment.additionalAddresses) &&
        Objects.equals(this.altReturnAddress, shipment.altReturnAddress) &&
        Objects.equals(this.carrierPayments, shipment.carrierPayments) &&
        Objects.equals(this.customs, shipment.customs) &&
        Objects.equals(this.documents, shipment.documents) &&
        Objects.equals(this.fromAddress, shipment.fromAddress) &&
        Objects.equals(this.hazmatDetails, shipment.hazmatDetails) &&
        Objects.equals(this.parcel, shipment.parcel) &&
        Objects.equals(this.parcelTrackingNumber, shipment.parcelTrackingNumber) &&
        Objects.equals(this.rates, shipment.rates) &&
        Objects.equals(this.references, shipment.references) &&
        Objects.equals(this.shipmentId, shipment.shipmentId) &&
        Objects.equals(this.shipmentOptions, shipment.shipmentOptions) &&
        Objects.equals(this.shipmentType, shipment.shipmentType) &&
        Objects.equals(this.soldToAddress, shipment.soldToAddress) &&
        Objects.equals(this.toAddress, shipment.toAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalAddresses, altReturnAddress, carrierPayments, customs, documents, fromAddress, hazmatDetails, parcel, parcelTrackingNumber, rates, references, shipmentId, shipmentOptions, shipmentType, soldToAddress, toAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shipment {\n");
    sb.append("    additionalAddresses: ").append(toIndentedString(additionalAddresses)).append("\n");
    sb.append("    altReturnAddress: ").append(toIndentedString(altReturnAddress)).append("\n");
    sb.append("    carrierPayments: ").append(toIndentedString(carrierPayments)).append("\n");
    sb.append("    customs: ").append(toIndentedString(customs)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    hazmatDetails: ").append(toIndentedString(hazmatDetails)).append("\n");
    sb.append("    parcel: ").append(toIndentedString(parcel)).append("\n");
    sb.append("    parcelTrackingNumber: ").append(toIndentedString(parcelTrackingNumber)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    shipmentOptions: ").append(toIndentedString(shipmentOptions)).append("\n");
    sb.append("    shipmentType: ").append(toIndentedString(shipmentType)).append("\n");
    sb.append("    soldToAddress: ").append(toIndentedString(soldToAddress)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

