/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * TrackingResponseScanDetailsList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-27T12:03:32.867+05:30[Asia/Calcutta]")
public class TrackingResponseScanDetailsList {
  public static final String SERIALIZED_NAME_EVENT_DATE = "eventDate";
  @SerializedName(SERIALIZED_NAME_EVENT_DATE)
  private LocalDate eventDate;

  public static final String SERIALIZED_NAME_EVENT_TIME = "eventTime";
  @SerializedName(SERIALIZED_NAME_EVENT_TIME)
  private String eventTime;

  public static final String SERIALIZED_NAME_EVENT_CITY = "eventCity";
  @SerializedName(SERIALIZED_NAME_EVENT_CITY)
  private String eventCity;

  public static final String SERIALIZED_NAME_EVENT_STATE_OR_PROVINCE = "eventStateOrProvince";
  @SerializedName(SERIALIZED_NAME_EVENT_STATE_OR_PROVINCE)
  private String eventStateOrProvince;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private Integer postalCode;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_SCAN_TYPE = "scanType";
  @SerializedName(SERIALIZED_NAME_SCAN_TYPE)
  private String scanType;

  public static final String SERIALIZED_NAME_SCAN_DESCRIPTION = "scanDescription";
  @SerializedName(SERIALIZED_NAME_SCAN_DESCRIPTION)
  private String scanDescription;

  public static final String SERIALIZED_NAME_PACKAGE_STATUS = "packageStatus";
  @SerializedName(SERIALIZED_NAME_PACKAGE_STATUS)
  private String packageStatus;


  public TrackingResponseScanDetailsList eventDate(LocalDate eventDate) {
    
    this.eventDate = eventDate;
    return this;
  }

   /**
   * Get eventDate
   * @return eventDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getEventDate() {
    return eventDate;
  }


  public void setEventDate(LocalDate eventDate) {
    this.eventDate = eventDate;
  }


  public TrackingResponseScanDetailsList eventTime(String eventTime) {
    
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventTime() {
    return eventTime;
  }


  public void setEventTime(String eventTime) {
    this.eventTime = eventTime;
  }


  public TrackingResponseScanDetailsList eventCity(String eventCity) {
    
    this.eventCity = eventCity;
    return this;
  }

   /**
   * Get eventCity
   * @return eventCity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventCity() {
    return eventCity;
  }


  public void setEventCity(String eventCity) {
    this.eventCity = eventCity;
  }


  public TrackingResponseScanDetailsList eventStateOrProvince(String eventStateOrProvince) {
    
    this.eventStateOrProvince = eventStateOrProvince;
    return this;
  }

   /**
   * Get eventStateOrProvince
   * @return eventStateOrProvince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventStateOrProvince() {
    return eventStateOrProvince;
  }


  public void setEventStateOrProvince(String eventStateOrProvince) {
    this.eventStateOrProvince = eventStateOrProvince;
  }


  public TrackingResponseScanDetailsList postalCode(Integer postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(Integer postalCode) {
    this.postalCode = postalCode;
  }


  public TrackingResponseScanDetailsList country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public TrackingResponseScanDetailsList scanType(String scanType) {
    
    this.scanType = scanType;
    return this;
  }

   /**
   * Get scanType
   * @return scanType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScanType() {
    return scanType;
  }


  public void setScanType(String scanType) {
    this.scanType = scanType;
  }


  public TrackingResponseScanDetailsList scanDescription(String scanDescription) {
    
    this.scanDescription = scanDescription;
    return this;
  }

   /**
   * Get scanDescription
   * @return scanDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScanDescription() {
    return scanDescription;
  }


  public void setScanDescription(String scanDescription) {
    this.scanDescription = scanDescription;
  }


  public TrackingResponseScanDetailsList packageStatus(String packageStatus) {
    
    this.packageStatus = packageStatus;
    return this;
  }

   /**
   * Get packageStatus
   * @return packageStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackageStatus() {
    return packageStatus;
  }


  public void setPackageStatus(String packageStatus) {
    this.packageStatus = packageStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingResponseScanDetailsList trackingResponseScanDetailsList = (TrackingResponseScanDetailsList) o;
    return Objects.equals(this.eventDate, trackingResponseScanDetailsList.eventDate) &&
        Objects.equals(this.eventTime, trackingResponseScanDetailsList.eventTime) &&
        Objects.equals(this.eventCity, trackingResponseScanDetailsList.eventCity) &&
        Objects.equals(this.eventStateOrProvince, trackingResponseScanDetailsList.eventStateOrProvince) &&
        Objects.equals(this.postalCode, trackingResponseScanDetailsList.postalCode) &&
        Objects.equals(this.country, trackingResponseScanDetailsList.country) &&
        Objects.equals(this.scanType, trackingResponseScanDetailsList.scanType) &&
        Objects.equals(this.scanDescription, trackingResponseScanDetailsList.scanDescription) &&
        Objects.equals(this.packageStatus, trackingResponseScanDetailsList.packageStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventDate, eventTime, eventCity, eventStateOrProvince, postalCode, country, scanType, scanDescription, packageStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingResponseScanDetailsList {\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventCity: ").append(toIndentedString(eventCity)).append("\n");
    sb.append("    eventStateOrProvince: ").append(toIndentedString(eventStateOrProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    scanType: ").append(toIndentedString(scanType)).append("\n");
    sb.append("    scanDescription: ").append(toIndentedString(scanDescription)).append("\n");
    sb.append("    packageStatus: ").append(toIndentedString(packageStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

