/*
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Errors;
import org.openapitools.client.model.Shipment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RateParcelsApi
 */
@Ignore
public class RateParcelsApiTest {

    private final RateParcelsApi api = new RateParcelsApi();

    
    /**
     * Use this operation to rate a parcel before you print and purchase a shipment label. You can rate a parcel for multiple services and multiple parcel types with a single API request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rateParcelTest() throws ApiException {
        Shipment shipment = null;
        Boolean xPBUnifiedErrorStructure = null;
        String xPBShipperRatePlan = null;
        String xPBIntegratorCarrierId = null;
        String xPBShipperCarrierAccountId = null;
        Boolean includeDeliveryCommitment = null;
        String carrier = null;
        Shipment response = api.rateParcel(shipment, xPBUnifiedErrorStructure, xPBShipperRatePlan, xPBIntegratorCarrierId, xPBShipperCarrierAccountId, includeDeliveryCommitment, carrier);

        // TODO: test validations
    }
    
}
